### Importing Libaries

In [27]:
import numpy as np # library to handle data in a vectorized manner

import pandas as pd # library for data analsysis
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

import json # library to handle JSON files

from geopy.geocoders import Nominatim # convert an address into latitude and longitude values

import requests # library to handle requests
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe


# import k-means from clustering stage
from sklearn.cluster import KMeans

import folium # map rendering library

import requests # library to handle requests

print('Libraries imported.')

Libraries imported.

### Reading Data

In [28]:
df = pd.read_csv('london-borough-profiles.csv', encoding = "ISO-8859-1")
df.shape

(38, 84)

In [29]:
df.head()

,Code,Area_name,Inner/_Outer_London,GLA_Population_Estimate_2017,GLA_Household_Estimate_2017,Inland_Area_(Hectares),Population_density_(per_hectare)_2017,"Average_Age,_2017","Proportion_of_population_aged_0-15,_2015","Proportion_of_population_of_working-age,_2015","Proportion_of_population_aged_65_and_over,_2015",Net_internal_migration_(2015),Net_international_migration_(2015),Net_natural_change_(2015),%_of_resident_population_born_abroad_(2015),Largest_migrant_population_by_country_of_birth_(2011),%_of_largest_migrant_population_(2011),Second_largest_migrant_population_by_country_of_birth_(2011),%_of_second_largest_migrant_population_(2011),Third_largest_migrant_population_by_country_of_birth_(2011),%_of_third_largest_migrant_population_(2011),%_of_population_from_BAME_groups_(2016),%_people_aged_3+_whose_main_language_is_not_English_(2011_Census),"Overseas_nationals_entering_the_UK_(NINo),_(2015/16)","New_migrant_(NINo)_rates,_(2015/16)",Largest_migrant_population_arrived_during_2015/16,Second_largest_migrant_population_arrived_during_2015/16,Third_largest_migrant_population_arrived_during_2015/16,Employment_rate_(%)_(2015),Male_employment_rate_(2015),Female_employment_rate_(2015),Unemployment_rate_(2015),Youth_Unemployment_(claimant)_rate_18-24_(Dec-15),Proportion_of_16-18_year_olds_who_are_NEET_(%)_(2014),Proportion_of_the_working-age_population_who_claim_out-of-work_benefits_(%)_(May-2016),%_working-age_with_a_disability_(2015),Proportion_of_working_age_people_with_no_qualifications_(%)_2015,Proportion_of_working_age_with_degree_or_equivalent_and_above_(%)_2015,"Gross_Annual_Pay,_(2016)",Gross_Annual_Pay_-_Male_(2016),Gross_Annual_Pay_-_Female_(2016),Modelled_Household_median_income_estimates_2012/13,%_adults_that_volunteered_in_past_12_months_(2010/11_to_2012/13),Number_of_jobs_by_workplace_(2014),%_of_employment_that_is_in_public_sector_(2014),"Jobs_Density,_2015","Number_of_active_businesses,_2015",Two-year_business_survival_rates_(started_in_2013),Crime_rates_per_thousand_population_2014/15,Fires_per_thousand_population_(2014),Ambulance_incidents_per_hundred_population_(2014),"Median_House_Price,_2015","Average_Band_D_Council_Tax_charge_(£),_2015/16",New_Homes_(net)_2015/16_(provisional),"Homes_Owned_outright,_(2014)_%","Being_bought_with_mortgage_or_loan,_(2014)_%","Rented_from_Local_Authority_or_Housing_Association,_(2014)_%","Rented_from_Private_landlord,_(2014)_%","%_of_area_that_is_Greenspace,_2005",Total_carbon_emissions_(2014),"Household_Waste_Recycling_Rate,_2014/15","Number_of_cars,_(2011_Census)","Number_of_cars_per_household,_(2011_Census)","%_of_adults_who_cycle_at_least_once_per_month,_2014/15","Average_Public_Transport_Accessibility_score,_2014","Achievement_of_5_or_more_A*-_C_grades_at_GCSE_or_equivalent_including_English_and_Maths,_2013/14",Rates_of_Children_Looked_After_(2016),%_of_pupils_whose_first_language_is_not_English_(2015),%_children_living_in_out-of-work_households_(2015),"Male_life_expectancy,_(2012-14)","Female_life_expectancy,_(2012-14)",Teenage_conception_rate_(2014),Life_satisfaction_score_2011-14_(out_of_10),Worthwhileness_score_2011-14_(out_of_10),Happiness_score_2011-14_(out_of_10),Anxiety_score_2011-14_(out_of_10),Childhood_Obesity_Prevalance_(%)_2015/16,People_aged_17+_with_diabetes_(%),Mortality_rate_from_causes_considered_preventable_2012/14,Political_control_in_council,Proportion_of_seats_won_by_Conservatives_in_2014_election,Proportion_of_seats_won_by_Labour_in_2014_election,Proportion_of_seats_won_by_Lib_Dems_in_2014_election,Turnout_at_2014_local_elections
0,E09000001,City of London,Inner London,8800,5326,290,30.3,43.2,11.4,73.1,15.5,-7,665,30,.,United States,2.8,France,2,Australia,1.9,27.5,17.1,975,152.2,India,France,United States,64.6,.,.,.,1.6,.,3.4,.,.,.,.,.,.,"£63,620",.,500400,3.4,84.3,26130,64.3,.,12.3,.,799999,931.2,80,.,.,.,.,4.8,1036,34.4,1692,0.4,16.9,7.9,78.6,101,.,7.9,.,.,.,6.6,7.1,6.0,5.6,NaN,2.6,129,.,.,.,.,.
1,E09000002,Barking and Dagenham,Outer London,209000,78188,"3,611",57.9,32.9,27.2,63.1,9.7,-1176,2509,2356,37.8,Nigeria,4.7,India,2.3,Pakistan,2.3,49.5,18.7,"7,538",59.1,Romania,Bulgaria,Lithuania,65.8,75.6,56.5,11,4.5,5.7,10.5,17.2,11.3,32.2,27886,30104,24602,"£29,420",20.5,58900,21.1,0.5,6560,73.0,83.4,3,13.7,243500,1354.03,730,16.4,27.4,35.9,20.3,33.6,644,23.4,56966,0.8,8.8,3,58,69,41.7,18.7,77.6,82.1,32.4,7.1,7.6,7.1,3.1,28.5,7.3,228,Lab,0,100,0,36.5
2,E09000003,Barnet,Outer London,389600,151423,"8,675",44.9,37.3,21.1,64.9,14.0,-3379,5407,2757,35.2,India,3.1,Poland,2.4,Iran,2,38.7,23.4,"13,094",53.1,Romania,Poland,Italy,68.5,74.5,62.9,8.5,1.9,2.5,6.2,14.9,5.2,49,33443,36475,31235,"£40,530",33.2,167300,18.7,0.7,26190,73.8,62.7,1.6,11.1,445000,1397.07,1460,32.4,25.2,11.1,31.1,41.3,1415,38,144717,1.1,7.4,3,67.3,35,46,9.3,82.1,85.1,12.8,7.5,7.8,7.4,2.8,20.7,6.0,134,Cons,50.8,.,1.6,40.5
3,E09000004,Bexley,Outer London,244300,97736,"6,058",40.3,39.0,20.6,62.9,16.6,413,760,1095,16.1,Nigeria,2.6,India,1.5,Ireland,0.9,21.4,6,"2,198",14.4,Romania,Poland,Nigeria,75.1,82.1,68.5,7.6,2.9,3.4,6.8,15.9,10.8,33.5,34350,37881,28924,"£36,990",22.1,80700,15.9,0.6,9075,73.5,51.8,2.3,11.8,275000,1472.43,-130,38.1,35.3,15.2,11.4,31.7,975,54,108507,1.2,10.6,2.6,60.3,46,32.6,12.6,80.4,84.4,19.5,7.4,7.7,7.2,3.3,22.7,6.9,164,Cons,71.4,23.8,0,39.6
4,E09000005,Brent,Outer London,332100,121048,"4,323",76.8,35.6,20.9,67.8,11.3,-7739,7640,3372,53.9,India,9.2,Poland,3.4,Ireland,2.9,64.9,37.2,"22,162",100.9,Romania,Italy,Portugal,69.5,76,62.6,7.5,3.1,2.6,8.3,17.7,6.2,45.1,29812,30129,29600,"£32,140",17.3,133600,17.6,0.6,15745,74.4,78.8,1.8,12.1,407250,1377.24,1050,22.2,22.6,20.4,34.8,21.9,1175,35.2,87802,0.8,7.9,3.7,60.1,45,37.6,13.7,80.1,85.1,18.5,7.3,7.4,7.2,2.9,24.3,7.9,169,Lab,9.5,88.9,1.6,36.3

### Setting FourSquare Parameters for Data Extraction

In [30]:
address = 'London, UK'

geolocator = Nominatim(user_agent="UK_explorer")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of London are {}, {}.'.format(latitude, longitude))

The geograpical coordinate of London are 51.5073219, -0.1276474.

In [31]:
CLIENT_ID = 'F1YFBED4KEJIR3G0US0YFQBJTPAWZF0XZX3DEKMBYUMDRJUB' 
CLIENT_SECRET = 'R2DVK0NNBBYQUGXZ42D5UXDZJD33HQZVKMQSUIRPTY5IOMUB' 
VERSION = '20180605' # Foursquare API version

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: F1YFBED4KEJIR3G0US0YFQBJTPAWZF0XZX3DEKMBYUMDRJUB
CLIENT_SECRET:R2DVK0NNBBYQUGXZ42D5UXDZJD33HQZVKMQSUIRPTY5IOMUB

In [32]:
# type your answer here
LIMIT = 100 # limit of number of venues returned by Foursquare API

radius = 500 # define radius

CLIENT_ID = 'F1YFBED4KEJIR3G0US0YFQBJTPAWZF0XZX3DEKMBYUMDRJUB' # your Foursquare ID
CLIENT_SECRET = 'R2DVK0NNBBYQUGXZ42D5UXDZJD33HQZVKMQSUIRPTY5IOMUB' # your Foursquare Secret
VERSION = '20180604'

# create URL
url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    latitude, 
    longitude, 
    radius, 
    LIMIT)
url # display URL

'https://api.foursquare.com/v2/venues/explore?&client_id=F1YFBED4KEJIR3G0US0YFQBJTPAWZF0XZX3DEKMBYUMDRJUB&client_secret=R2DVK0NNBBYQUGXZ42D5UXDZJD33HQZVKMQSUIRPTY5IOMUB&v=20180604&ll=51.5073219,-0.1276474&radius=500&limit=100'

In [33]:
result = requests.get(url).json()
result

{'meta': {'code': 200, 'requestId': '5e4a790f60ba08001b7bf51c'},
 'response': {'suggestedFilters': {'header': 'Tap to show:',
   'filters': [{'name': 'Open now', 'key': 'openNow'}]},
  'headerLocation': 'Westminster',
  'headerFullLocation': 'Westminster, London',
  'headerLocationGranularity': 'neighborhood',
  'totalResults': 153,
  'suggestedBounds': {'ne': {'lat': 51.5118219045,
    'lng': -0.12043098456785678},
   'sw': {'lat': 51.5028218955, 'lng': -0.1348638154321432}},
  'groups': [{'type': 'Recommended Places',
    'name': 'recommended',
    'items': [{'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4ac518cdf964a520e6a520e3',
       'name': 'National Gallery',
       'location': {'address': 'Trafalgar Sq',
        'lat': 51.50887601013219,
        'lng': -0.1284778118133545,
        'labeledLatLngs': [{'label': 'display',
          'lat': 51.50887601013219,
          'lng': -0.1284778118133545}],
        'distance': 182,
        'postalCode': 'WC2N 5DN',
        'cc': 'GB',
        'city': 'London',
        'state': 'Greater London',
        'country': 'United Kingdom',
        'formattedAddress': ['Trafalgar Sq',
         'London',
         'Greater London',
         'WC2N 5DN',
         'United Kingdom']},
       'categories': [{'id': '4bf58dd8d48988d18f941735',
         'name': 'Art Museum',
         'pluralName': 'Art Museums',
         'shortName': 'Art Museum',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/arts_entertainment/museum_art_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []},
       'venuePage': {'id': '51313653'}},
      'referralId': 'e-0-4ac518cdf964a520e6a520e3-0'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4ac518cef964a520f9a520e3',
       'name': 'Trafalgar Square',
       'location': {'address': 'Trafalgar Sq',
        'lat': 51.507987,
        'lng': -0.128048,
        'labeledLatLngs': [{'label': 'display',
          'lat': 51.507987,
          'lng': -0.128048}],
        'distance': 79,
        'postalCode': 'WC2N 5DX',
        'cc': 'GB',
        'city': 'London',
        'state': 'Greater London',
        'country': 'United Kingdom',
        'formattedAddress': ['Trafalgar Sq',
         'London',
         'Greater London',
         'WC2N 5DX',
         'United Kingdom']},
       'categories': [{'id': '4bf58dd8d48988d164941735',
         'name': 'Plaza',
         'pluralName': 'Plazas',
         'shortName': 'Plaza',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/parks_outdoors/plaza_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-4ac518cef964a520f9a520e3-1'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '50aa7c98e4b0d042f9f0bd59',
       'name': 'East Trafalgar Square Fountain',
       'location': {'address': 'Trafalgar Sq',
        'lat': 51.508088051633095,
        'lng': -0.12769997119903564,
        'labeledLatLngs': [{'label': 'display',
          'lat': 51.508088051633095,
          'lng': -0.12769997119903564}],
        'distance': 85,
        'postalCode': 'WC2N 5DN',
        'cc': 'GB',
        'city': 'London',
        'state': 'Greater London',
        'country': 'United Kingdom',
        'formattedAddress': ['Trafalgar Sq',
         'London',
         'Greater London',
         'WC2N 5DN',
         'United Kingdom']},
       'categories': [{'id': '56aa371be4b08b9a8d573547',
         'name': 'Fountain',
         'pluralName': 'Fountains',
         'shortName': 'Fountain',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/parks_outdoors/plaza_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-50aa7c98e4b0d042f9f0bd59-2'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '5320a0a6498e8dd49f5aa981',
       'name': 'Sainsbury Wing National Gallery',
       'location': {'address': 'Trafalgar Sq',
        'lat': 51.508383964576424,
        'lng': -0.1290009759071342,
        'labeledLatLngs': [{'label': 'display',
          'lat': 51.508383964576424,
          'lng': -0.1290009759071342}],
        'distance': 150,
        'postalCode': 'WC2N 5DN',
        'cc': 'GB',
        'city': 'London',
        'state': 'Greater London',
        'country': 'United Kingdom',
        'formattedAddress': ['Trafalgar Sq',
         'London',
         'Greater London',
         'WC2N 5DN',
         'United Kingdom']},
       'categories': [{'id': '4bf58dd8d48988d18f941735',
         'name': 'Art Museum',
         'pluralName': 'Art Museums',
         'shortName': 'Art Museum',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/arts_entertainment/museum_art_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-5320a0a6498e8dd49f5aa981-3'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '50aa6e60e4b078585157bbb5',
       'name': 'Trafalgar Square Lions',
       'location': {'address': 'Trafalgar Sq',
        'lat': 51.50764064540292,
        'lng': -0.12788772583007812,
        'labeledLatLngs': [{'label': 'display',
          'lat': 51.50764064540292,
          'lng': -0.12788772583007812}],
        'distance': 39,
        'postalCode': 'WC2N 5DN',
        'cc': 'GB',
        'city': 'London',
        'state': 'Greater London',
        'country': 'United Kingdom',
        'formattedAddress': ['Trafalgar Sq',
         'London',
         'Greater London',
         'WC2N 5DN',
         'United Kingdom']},
       'categories': [{'id': '52e81612bcbc57f1066b79ed',
         'name': 'Outdoor Sculpture',
         'pluralName': 'Outdoor Sculptures',
         'shortName': 'Outdoor Sculpture',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/parks_outdoors/sculpture_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-50aa6e60e4b078585157bbb5-4'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '509e51b6e4b03f3cc1f3f56c',
       'name': 'ESPA Life at Corinthia',
       'location': {'address': '10 Whitehall Pl',
        'lat': 51.506401908218095,
        'lng': -0.12511432170867917,
        'labeledLatLngs': [{'label': 'display',
          'lat': 51.506401908218095,
          'lng': -0.12511432170867917}],
        'distance': 203,
        'postalCode': 'SW1A 2BD',
        'cc': 'GB',
        'city': 'London',
        'state': 'Greater London',
        'country': 'United Kingdom',
        'formattedAddress': ['10 Whitehall Pl',
         'London',
         'Greater London',
         'SW1A 2BD',
         'United Kingdom']},
       'categories': [{'id': '4bf58dd8d48988d1ed941735',
         'name': 'Spa',
         'pluralName': 'Spas',
         'shortName': 'Spa',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/shops/spa_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-509e51b6e4b03f3cc1f3f56c-5'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4b9a4eb0f964a5202bab35e3',
       'name': 'St Martin-in-the-Fields',
       'location': {'address': '5 Trafalgar Sq',
        'lat': 51.508745742823905,
        'lng': -0.12650689522425146,
        'labeledLatLngs': [{'label': 'display',
          'lat': 51.508745742823905,
          'lng': -0.12650689522425146}],
        'distance': 177,
        'postalCode': 'WC2N 4JJ',
        'cc': 'GB',
        'city': 'London',
        'state': 'Greater London',
        'country': 'United Kingdom',
        'formattedAddress': ['5 Trafalgar Sq',
         'London',
         'Greater London',
         'WC2N 4JJ',
         'United Kingdom']},
       'categories': [{'id': '4bf58dd8d48988d132941735',
         'name': 'Church',
         'pluralName': 'Churches',
         'shortName': 'Church',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/building/religious_church_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-4b9a4eb0f964a5202bab35e3-6'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4ae5c61ff964a520efa121e3',
       'name': "Nelson's Column",
       'location': {'address': 'Trafalgar Sq',
        'lat': 51.50774415021993,
        'lng': -0.1279306411743164,
        'labeledLatLngs': [{'label': 'display',
          'lat': 51.50774415021993,
          'lng': -0.1279306411743164}],
        'distance': 50,
        'postalCode': 'WC2N 5DN',
        'cc': 'GB',
        'city': 'London',
        'state': 'Greater London',
        'country': 'United Kingdom',
        'formattedAddress': ['Trafalgar Sq',
         'London',
         'Greater London',
         'WC2N 5DN',
         'United Kingdom']},
       'categories': [{'id': '4bf58dd8d48988d12d941735',
         'name': 'Monument / Landmark',
         'pluralName': 'Monuments / Landmarks',
         'shortName': 'Landmark',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/building/government_monument_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-4ae5c61ff964a520efa121e3-7'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4d274945d86aa09024d41dc0',
       'name': 'Corinthia Hotel',
       'location': {'address': 'Whitehall Pl',
        'lat': 51.506606723475606,
        'lng': -0.12446016991110907,
        'labeledLatLngs': [{'label': 'display',
          'lat': 51.506606723475606,
          'lng': -0.12446016991110907}],
        'distance': 234,
        'postalCode': 'SW1A 2BD',
        'cc': 'GB',
        'city': 'London',
        'state': 'Greater London',
        'country': 'United Kingdom',
        'formattedAddress': ['Whitehall Pl',
         'London',
         'Greater London',
         'SW1A 2BD',
         'United Kingdom']},
       'categories': [{'id': '4bf58dd8d48988d1fa931735',
         'name': 'Hotel',
         'pluralName': 'Hotels',
         'shortName': 'Hotel',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/travel/hotel_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-4d274945d86aa09024d41dc0-8'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4ac518d2f964a52047a720e3',
       'name': 'National Portrait Gallery',
       'location': {'address': "St. Martin's Pl",
        'lat': 51.50943806358441,
        'lng': -0.1280324346985737,
        'distance': 237,
        'postalCode': 'WC2H 0HE',
        'cc': 'GB',
        'city': 'London',
        'state': 'Greater London',
        'country': 'United Kingdom',
        'formattedAddress': ["St. Martin's Pl",
         'London',
         'Greater London',
         'WC2H 0HE',
         'United Kingdom']},
       'categories': [{'id': '4bf58dd8d48988d1e2931735',
         'name': 'Art Gallery',
         'pluralName': 'Art Galleries',
         'shortName': 'Art Gallery',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/arts_entertainment/artgallery_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []},
       'venuePage': {'id': '95725206'}},
      'referralId': 'e-0-4ac518d2f964a52047a720e3-9'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4ac518e7f964a52061ab20e3',
       'name': 'Trafalgar Studios',
       'location': {'address': '14 Whitehall',
        'lat': 51.50665145618764,
        'lng': -0.12737761183304314,
        'labeledLatLngs': [{'label': 'display',
          'lat': 51.50665145618764,
          'lng': -0.12737761183304314}],
        'distance': 76,
        'postalCode': 'SW1A 2DY',
        'cc': 'GB',
        'city': 'London',
        'state': 'Greater London',
        'country': 'United Kingdom',
        'formattedAddress': ['14 Whitehall',
         'London',
         'Greater London',
         'SW1A 2DY',
         'United Kingdom']},
       'categories': [{'id': '4bf58dd8d48988d137941735',
         'name': 'Theater',
         'pluralName': 'Theaters',
         'shortName': 'Theater',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/arts_entertainment/performingarts_theater_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-4ac518e7f964a52061ab20e3-10'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4bf67863004ed13aa37342a0',
       'name': 'Waterstones',
       'location': {'address': 'The Grand Building, Trafalgar Square',
        'lat': 51.50764972496243,
        'lng': -0.12712953878194402,
        'labeledLatLngs': [{'label': 'display',
          'lat': 51.50764972496243,
          'lng': -0.12712953878194402}],
        'distance': 51,
        'postalCode': 'WC2N 5EJ',
        'cc': 'GB',
        'city': 'London',
        'state': 'Greater London',
        'country': 'United Kingdom',
        'formattedAddress': ['The Grand Building, Trafalgar Square',
         'London',
         'Greater London',
         'WC2N 5EJ',
         'United Kingdom']},
       'categories': [{'id': '4bf58dd8d48988d114951735',
         'name': 'Bookstore',
         'pluralName': 'Bookstores',
         'shortName': 'Bookstore',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/shops/bookstore_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-4bf67863004ed13aa37342a0-11'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4b472029f964a520aa2b26e3',
       'name': 'George Washington Statue',
       'location': {'address': 'Trafalgar Sq',
        'lat': 51.508658989024,
        'lng': -0.12770533561706543,
        'labeledLatLngs': [{'label': 'display',
          'lat': 51.508658989024,
          'lng': -0.12770533561706543}],
        'distance': 148,
        'postalCode': 'WC2N 5DN',
        'cc': 'GB',
        'city': 'London',
        'state': 'Greater London',
        'country': 'United Kingdom',
        'formattedAddress': ['Trafalgar Sq',
         'London',
         'Greater London',
         'WC2N 5DN',
         'United Kingdom']},
       'categories': [{'id': '52e81612bcbc57f1066b79ed',
         'name': 'Outdoor Sculpture',
         'pluralName': 'Outdoor Sculptures',
         'shortName': 'Outdoor Sculpture',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/parks_outdoors/sculpture_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-4b472029f964a520aa2b26e3-12'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4ac518b9f964a520b6a120e3',
       'name': 'Institute of Contemporary Arts (ICA)',
       'location': {'address': 'The Mall',
        'lat': 51.50626501066752,
        'lng': -0.13081669807434082,
        'labeledLatLngs': [{'label': 'display',
          'lat': 51.50626501066752,
          'lng': -0.13081669807434082}],
        'distance': 249,
        'postalCode': 'SW1Y 5AH',
        'cc': 'GB',
        'city': 'London',
        'state': 'Greater London',
        'country': 'United Kingdom',
        'formattedAddress': ['The Mall',
         'London',
         'Greater London',
         'SW1Y 5AH',
         'United Kingdom']},
       'categories': [{'id': '4bf58dd8d48988d1e2931735',
         'name': 'Art Gallery',
         'pluralName': 'Art Galleries',
         'shortName': 'Art Gallery',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/arts_entertainment/artgallery_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []},
       'venuePage': {'id': '140753416'}},
      'referralId': 'e-0-4ac518b9f964a520b6a120e3-13'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '53bab96d498e7e355fb53d6c',
       'name': 'Barrafina',
       'location': {'address': '10 Adelaide St',
        'crossStreet': 'William IV St',
        'lat': 51.509426526936956,
        'lng': -0.1258944349847769,
        'labeledLatLngs': [{'label': 'display',
          'lat': 51.509426526936956,
          'lng': -0.1258944349847769}],
        'distance': 263,
        'postalCode': 'WC2N 4HZ',
        'cc': 'GB',
        'city': 'London',
        'state': 'Greater London',
        'country': 'United Kingdom',
        'formattedAddress': ['10 Adelaide St (William IV St)',
         'London',
         'Greater London',
         'WC2N 4HZ',
         'United Kingdom']},
       'categories': [{'id': '4bf58dd8d48988d150941735',
         'name': 'Spanish Restaurant',
         'pluralName': 'Spanish Restaurants',
         'shortName': 'Spanish',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/spanish_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-53bab96d498e7e355fb53d6c-14'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '52764ec8498e83fe786a0595',
       'name': 'Afternoon Tea at the Corinthia Hotel',
       'location': {'address': '10 Whitehall Pl',
        'lat': 51.506572305834275,
        'lng': -0.1243504500869256,
        'labeledLatLngs': [{'label': 'display',
          'lat': 51.506572305834275,
          'lng': -0.1243504500869256}],
        'distance': 243,
        'postalCode': 'SW1A 2BD',
        'cc': 'GB',
        'city': 'London',
        'state': 'Greater London',
        'country': 'United Kingdom',
        'formattedAddress': ['10 Whitehall Pl',
         'London',
         'Greater London',
         'SW1A 2BD',
         'United Kingdom']},
       'categories': [{'id': '4bf58dd8d48988d1dc931735',

In [34]:
# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

In [35]:
venues = result['response']['groups'][0]['items']
    
nearby_venues = json_normalize(venues) # flatten JSON

# filter columns
filtered_columns = ['venue.name', 'venue.categories', 'venue.location.lat', 'venue.location.lng']
nearby_venues =nearby_venues.loc[:, filtered_columns]

# filter the category for each row
nearby_venues['venue.categories'] = nearby_venues.apply(get_category_type, axis=1)

# clean columns
nearby_venues.columns = [col.split(".")[-1] for col in nearby_venues.columns]

nearby_venues

,name,categories,lat,lng
0,National Gallery,Art Museum,51.508876,-0.128478
1,Trafalgar Square,Plaza,51.507987,-0.128048
2,East Trafalgar Square Fountain,Fountain,51.508088,-0.127700
3,Sainsbury Wing National Gallery,Art Museum,51.508384,-0.129001
4,Trafalgar Square Lions,Outdoor Sculpture,51.507641,-0.127888
5,ESPA Life at Corinthia,Spa,51.506402,-0.125114
6,St Martin-in-the-Fields,Church,51.508746,-0.126507
7,Nelson's Column,Monument / Landmark,51.507744,-0.127931
8,Corinthia Hotel,Hotel,51.506607,-0.124460
9,National Portrait Gallery,Art Gallery,51.509438,-0.128032
10,Trafalgar Studios,Theater,51.506651,-0.127378
11,Waterstones,Bookstore,51.507650,-0.127130
12,George Washington Statue,Outdoor Sculpture,51.508659,-0.127705
13,Institute of Contemporary Arts (ICA),Art Gallery,51.506265,-0.130817
14,Barrafina,Spanish Restaurant,51.509427,-0.125894
15,Afternoon Tea at the Corinthia Hotel,Tea Room,51.506572,-0.124350
16,Haymarket Hotel,Hotel,51.508267,-0.131315
17,Tandoor Chop House,North Indian Restaurant,51.509192,-0.125638
18,Bancone,Italian Restaurant,51.509529,-0.126434
19,Minamoto Kitchoan,Candy Store,51.508652,-0.125480
20,Kerridge’s Bar & Grill,Restaurant,51.506728,-0.124520
21,Horse Guards Parade,Plaza,51.504847,-0.126590
22,Thai Square,Thai Restaurant,51.507656,-0.129830
23,English National Opera,Opera House,51.509804,-0.126945
24,The London Coliseum,Theater,51.509846,-0.127005
25,Café In The Crypt,Café,51.508962,-0.126729
26,The Admiralty,Pub,51.507303,-0.128847
27,The Harp,Pub,51.509719,-0.125943
28,Gordon's Wine Bar,Wine Bar,51.507911,-0.123293
29,Her Majesty's Theatre,Theater,51.508289,-0.131641
30,ICA Cinema,Indie Movie Theater,51.506018,-0.131068
31,The Royal Horseguards,Hotel,51.506127,-0.124224
32,Terroirs,Wine Bar,51.509547,-0.125250
33,National Portrait Gallery Shop,Gift Shop,51.509356,-0.127373
34,Nutshell,Persian Restaurant,51.509632,-0.126605
35,Pret A Manger,Sandwich Place,51.508114,-0.129910
36,Notes Music & Coffee,Coffee Shop,51.509696,-0.126985
37,Sofitel London St James,Hotel,51.507636,-0.132367
38,Mall Galleries,Art Gallery,51.506370,-0.129776
39,Whitehall Gardens,Garden,51.506354,-0.122900
40,Five Guys,Burger Joint,51.508520,-0.124363
41,Amorino,Ice Cream Shop,51.510427,-0.128401
42,Dover Street Market,Boutique,51.508981,-0.131867
43,The Household Cavalry Museum,History Museum,51.504869,-0.126594
44,MOD Pizza,Pizza Place,51.510011,-0.129131
45,Brumus,French Restaurant,51.508198,-0.131485
46,The Northall,English Restaurant,51.506599,-0.123821
47,Japan Centre,Japanese Restaurant,51.509761,-0.131273
48,St. Martin's Lane Hotel,Hotel,51.510526,-0.126705
49,Leicester Square Garden,Garden,51.510361,-0.130127
50,Ole & Steen,Bakery,51.509219,-0.132597
51,Wahaca,Mexican Restaurant,51.510221,-0.124524
52,The Whisky Exchange,Liquor Store,51.509974,-0.123713
53,The London Beer House,Bar,51.508214,-0.132578
54,Victoria Embankment Gardens,Park,51.508135,-0.122079
55,Steak & Co.,Steakhouse,51.509923,-0.128494
56,Harold Pinter Theatre,Theater,51.509443,-0.131644
57,hub by Premier Inn London Covent Garden,Hotel,51.510036,-0.127111
58,Milos,Greek Restaurant,51.508117,-0.133341
59,Mr Fogg's Society of Exploration,Cocktail Bar,51.509769,-0.123532
60,Kanada-Ya,Ramen Restaurant,51.509359,-0.132215
61,Retro Bar,Gay Bar,51.509153,-0.123533
62,Leicester Square,Plaza,51.510519,-0.130098
63,Prince of Wales Theatre,Theater,51.510132,-0.131594
64,The LEGO Store,Toy / Game Store,51.510497,-0.131001
65,Superdrug,Pharmacy,51.509174,-0.124054
66,J Sheekey,Seafood Restaurant,51.510899,-0.127797
67,La Gelatiera,Ice Cream Shop,51.511046,-0.126828
68,Noel Coward Theatre,Theater,51.511042,-0.127619
69,Sandwich Centre,Sandwich Place,51.508174,-0.132451
70,St James Bar,Cocktail Bar,51.507442,-0.132402
71,Scully,Restaurant,51.508744,-0.133083
72,Gymbox,Gym / Fitness Center,51.510468,-0.126803
73,So Spa,Spa,51.507601,-0.132690
74,Lao Café,Asian Restaurant,51.509987,-0.124891
75,Mr Fogg's Tavern,Pub,51.511000,-0.126952
76,Rochelle Canteen at ICA,English Restaurant,51.506258,-0.130640
77,Guards Memorial,Monument / Landmark,51.504595,-0.129438
78,Machiya,Japanese Restaurant,51.509413,-0.131994
79,Flat Iron,Steakhouse,51.510841,-0.124093
80,The Alchemist,Cocktail Bar,51.511458,-0.126955
81,The Z Hotel Piccadilly,Hotel,51.509009,-0.131564
82,Nando's,Portuguese Restaurant,51.510325,-0.124604
83,The Espresso Room,Coffee Shop,51.511074,-0.126568
84,Adelphi Theatre,Theater,51.510383,-0.123068
85,Mr Fogg's Gin Parlour,Speakeasy,51.511012,-0.126945
86,WA Cafe,Café,51.511009,-0.126614
87,Simit Sarayı,Bagel Shop,51.510597,-0.130643
88,Amorino,Ice Cream Shop,51.511510,-0.125794
89,Blame Gloria,Bar,51.510905,-0.124615
90,The Royal Trafalgar by Thistle,Hotel,51.509087,-0.130328
91,Byron,Burger Joint,51.508871,-0.131699
92,The Original London Sightseeing Tour,Tour Provider,51.508011,-0.130052
93,The Comedy Store,Comedy Club,51.510234,-0.132507
94,Imperial Treasure Fine Chinese Cuisine,Chinese Restaurant,51.507935,-0.132977
95,M&M's World,Candy Store,51.510599,-0.131149
96,Wyndham's Theatre,Theater,51.511072,-0.127990
97,Busaba Eathai,Thai Restaurant,51.509987,-0.131019
98,Sticks'n'Sushi,Sushi Restaurant,51.511038,-0.123655
99,The Port House,Wine Bar,51.509893,-0.123001

### Getting further data from web and cleaning the data

In [36]:
df2 = pd.read_html('https://en.wikipedia.org/wiki/List_of_London_boroughs')[0]

In [37]:
df2.head()

,Borough,Inner,Status,Local authority,Political control,Headquarters,Area (sq mi),Population (2013 est)[1],Co-ordinates,Nr. in map
0,Barking and Dagenham [note 1],NaN,NaN,Barking and Dagenham London Borough Council,Labour,"Town Hall, 1 Town Square",13.93,194352,51°33′39″N 0°09′21″E﻿ / ﻿51.5607°N 0.1557°E,25
1,Barnet,NaN,NaN,Barnet London Borough Council,Conservative,"North London Business Park, Oakleigh Road South",33.49,369088,51°37′31″N 0°09′06″W﻿ / ﻿51.6252°N 0.1517°W,31
2,Bexley,NaN,NaN,Bexley London Borough Council,Conservative,"Civic Offices, 2 Watling Street",23.38,236687,51°27′18″N 0°09′02″E﻿ / ﻿51.4549°N 0.1505°E,23
3,Brent,NaN,NaN,Brent London Borough Council,Labour,"Brent Civic Centre, Engineers Way",16.70,317264,51°33′32″N 0°16′54″W﻿ / ﻿51.5588°N 0.2817°W,12
4,Bromley,NaN,NaN,Bromley London Borough Council,Conservative,"Civic Centre, Stockwell Close",57.97,317899,51°24′14″N 0°01′11″E﻿ / ﻿51.4039°N 0.0198°E,20

In [38]:
df2['Co-ordinates'] = df2['Co-ordinates'].str.split('/').str[1]
df2.head()

,Borough,Inner,Status,Local authority,Political control,Headquarters,Area (sq mi),Population (2013 est)[1],Co-ordinates,Nr. in map
0,Barking and Dagenham [note 1],NaN,NaN,Barking and Dagenham London Borough Council,Labour,"Town Hall, 1 Town Square",13.93,194352,﻿51.5607°N 0.1557°E,25
1,Barnet,NaN,NaN,Barnet London Borough Council,Conservative,"North London Business Park, Oakleigh Road South",33.49,369088,﻿51.6252°N 0.1517°W,31
2,Bexley,NaN,NaN,Bexley London Borough Council,Conservative,"Civic Offices, 2 Watling Street",23.38,236687,﻿51.4549°N 0.1505°E,23
3,Brent,NaN,NaN,Brent London Borough Council,Labour,"Brent Civic Centre, Engineers Way",16.70,317264,﻿51.5588°N 0.2817°W,12
4,Bromley,NaN,NaN,Bromley London Borough Council,Conservative,"Civic Centre, Stockwell Close",57.97,317899,﻿51.4039°N 0.0198°E,20

In [39]:
df2['Latitude'] = df2['Co-ordinates'].str.split(' ').str[1]
df2['Longitude'] =df2['Co-ordinates'].str.split(' ').str[2]

In [40]:
df2

,Borough,Inner,Status,Local authority,Political control,Headquarters,Area (sq mi),Population (2013 est)[1],Co-ordinates,Nr. in map,Latitude,Longitude
0,Barking and Dagenham [note 1],NaN,NaN,Barking and Dagenham London Borough Council,Labour,"Town Hall, 1 Town Square",13.93,194352,﻿51.5607°N 0.1557°E,25,﻿51.5607°N,0.1557°E
1,Barnet,NaN,NaN,Barnet London Borough Council,Conservative,"North London Business Park, Oakleigh Road South",33.49,369088,﻿51.6252°N 0.1517°W,31,﻿51.6252°N,0.1517°W
2,Bexley,NaN,NaN,Bexley London Borough Council,Conservative,"Civic Offices, 2 Watling Street",23.38,236687,﻿51.4549°N 0.1505°E,23,﻿51.4549°N,0.1505°E
3,Brent,NaN,NaN,Brent London Borough Council,Labour,"Brent Civic Centre, Engineers Way",16.70,317264,﻿51.5588°N 0.2817°W,12,﻿51.5588°N,0.2817°W
4,Bromley,NaN,NaN,Bromley London Borough Council,Conservative,"Civic Centre, Stockwell Close",57.97,317899,﻿51.4039°N 0.0198°E,20,﻿51.4039°N,0.0198°E
5,Camden,NaN,NaN,Camden London Borough Council,Labour,"Camden Town Hall, Judd Street",8.40,229719,﻿51.5290°N 0.1255°W,11,﻿51.5290°N,0.1255°W
6,Croydon,NaN,NaN,Croydon London Borough Council,Labour,"Bernard Weatherill House, Mint Walk",33.41,372752,﻿51.3714°N 0.0977°W,19,﻿51.3714°N,0.0977°W
7,Ealing,NaN,NaN,Ealing London Borough Council,Labour,"Perceval House, 14-16 Uxbridge Road",21.44,342494,﻿51.5130°N 0.3089°W,13,﻿51.5130°N,0.3089°W
8,Enfield,NaN,NaN,Enfield London Borough Council,Labour,"Civic Centre, Silver Street",31.74,320524,﻿51.6538°N 0.0799°W,30,﻿51.6538°N,0.0799°W
9,Greenwich [note 2],[note 3],Royal,Greenwich London Borough Council,Labour,"Woolwich Town Hall, Wellington Street",18.28,264008,﻿51.4892°N 0.0648°E,22,﻿51.4892°N,0.0648°E
10,Hackney,NaN,NaN,Hackney London Borough Council,Labour,"Hackney Town Hall, Mare Street",7.36,257379,﻿51.5450°N 0.0553°W,9,﻿51.5450°N,0.0553°W
11,Hammersmith and Fulham [note 4],NaN,NaN,Hammersmith and Fulham London Borough Council,Labour,"Town Hall, King Street",6.33,178685,﻿51.4927°N 0.2339°W,4,﻿51.4927°N,0.2339°W
12,Haringey,[note 3],NaN,Haringey London Borough Council,Labour,"Civic Centre, High Road",11.42,263386,﻿51.6000°N 0.1119°W,29,﻿51.6000°N,0.1119°W
13,Harrow,NaN,NaN,Harrow London Borough Council,Labour,"Civic Centre, Station Road",19.49,243372,﻿51.5898°N 0.3346°W,32,﻿51.5898°N,0.3346°W
14,Havering,NaN,NaN,Havering London Borough Council,Conservative (council NOC),"Town Hall, Main Road",43.35,242080,﻿51.5812°N 0.1837°E,24,﻿51.5812°N,0.1837°E
15,Hillingdon,NaN,NaN,Hillingdon London Borough Council,Conservative,"Civic Centre, High Street",44.67,286806,﻿51.5441°N 0.4760°W,33,﻿51.5441°N,0.4760°W
16,Hounslow,NaN,NaN,Hounslow London Borough Council,Labour,"Hounslow House, 7 Bath Road",21.61,262407,﻿51.4746°N 0.3680°W,14,﻿51.4746°N,0.3680°W
17,Islington,NaN,NaN,Islington London Borough Council,Labour,"Municipal Offices, 222 Upper Street",5.74,215667,﻿51.5416°N 0.1022°W,10,﻿51.5416°N,0.1022°W
18,Kensington and Chelsea,NaN,Royal,Kensington and Chelsea London Borough Council,Conservative,"The Town Hall, Hornton Street",4.68,155594,﻿51.5020°N 0.1947°W,3,﻿51.5020°N,0.1947°W
19,Kingston upon Thames,NaN,Royal,Kingston upon Thames London Borough Council,Liberal Democrat,"Guildhall, High Street",14.38,166793,﻿51.4085°N 0.3064°W,16,﻿51.4085°N,0.3064°W
20,Lambeth,NaN,NaN,Lambeth London Borough Council,Labour,"Lambeth Town Hall, Brixton Hill",10.36,314242,﻿51.4607°N 0.1163°W,6,﻿51.4607°N,0.1163°W
21,Lewisham,NaN,NaN,Lewisham London Borough Council,Labour,"Town Hall, 1 Catford Road",13.57,286180,﻿51.4452°N 0.0209°W,21,﻿51.4452°N,0.0209°W
22,Merton,NaN,NaN,Merton London Borough Council,Labour,"Civic Centre, London Road",14.52,203223,﻿51.4014°N 0.1958°W,17,﻿51.4014°N,0.1958°W
23,Newham,[note 3],NaN,Newham London Borough Council,Labour,"Newham Dockside, 1000 Dockside Road",13.98,318227,﻿51.5077°N 0.0469°E,27,﻿51.5077°N,0.0469°E
24,Redbridge,NaN,NaN,Redbridge London Borough Council,Labour,"Town Hall, 128-142 High Road",21.78,288272,﻿51.5590°N 0.0741°E,26,﻿51.5590°N,0.0741°E
25,Richmond upon Thames,NaN,NaN,Richmond upon Thames London Borough Council,Liberal Democrat,"Civic Centre, 44 York Street",22.17,191365,﻿51.4479°N 0.3260°W,15,﻿51.4479°N,0.3260°W
26,Southwark,NaN,NaN,Southwark London Borough Council,Labour,160 Tooley Street,11.14,298464,﻿51.5035°N 0.0804°W,7,﻿51.5035°N,0.0804°W
27,Sutton,NaN,NaN,Sutton London Borough Council,Liberal Democrat,"Civic Offices, St Nicholas Way",16.93,195914,﻿51.3618°N 0.1945°W,18,﻿51.3618°N,0.1945°W
28,Tower Hamlets,NaN,NaN,Tower Hamlets London Borough Council,Labour,"Town Hall, Mulberry Place, 5 Clove Crescent",7.63,272890,﻿51.5099°N 0.0059°W,8,﻿51.5099°N,0.0059°W
29,Waltham Forest,NaN,NaN,Waltham Forest London Borough Council,Labour,"Waltham Forest Town Hall, Forest Road",14.99,265797,﻿51.5908°N 0.0134°W,28,﻿51.5908°N,0.0134°W
30,Wandsworth,NaN,NaN,Wandsworth London Borough Council,Conservative,"The Town Hall, Wandsworth High Street",13.23,310516,﻿51.4567°N 0.1910°W,5,﻿51.4567°N,0.1910°W
31,Westminster,NaN,City,Westminster City Council,Conservative,"Westminster City Hall, 64 Victoria Street",8.29,226841,﻿51.4973°N 0.1372°W,2,﻿51.4973°N,0.1372°W

In [41]:
df2['Latitude'] = df2['Latitude'].str.split('°').str[0]
df2['Longitude'] =df2['Longitude'].str.split('°').str[0]
df2.head()

,Borough,Inner,Status,Local authority,Political control,Headquarters,Area (sq mi),Population (2013 est)[1],Co-ordinates,Nr. in map,Latitude,Longitude
0,Barking and Dagenham [note 1],NaN,NaN,Barking and Dagenham London Borough Council,Labour,"Town Hall, 1 Town Square",13.93,194352,﻿51.5607°N 0.1557°E,25,﻿51.5607,0.1557
1,Barnet,NaN,NaN,Barnet London Borough Council,Conservative,"North London Business Park, Oakleigh Road South",33.49,369088,﻿51.6252°N 0.1517°W,31,﻿51.6252,0.1517
2,Bexley,NaN,NaN,Bexley London Borough Council,Conservative,"Civic Offices, 2 Watling Street",23.38,236687,﻿51.4549°N 0.1505°E,23,﻿51.4549,0.1505
3,Brent,NaN,NaN,Brent London Borough Council,Labour,"Brent Civic Centre, Engineers Way",16.70,317264,﻿51.5588°N 0.2817°W,12,﻿51.5588,0.2817
4,Bromley,NaN,NaN,Bromley London Borough Council,Conservative,"Civic Centre, Stockwell Close",57.97,317899,﻿51.4039°N 0.0198°E,20,﻿51.4039,0.0198

In [42]:
df3 =df2[['Borough', 'Latitude', 'Longitude']]
df3.head()

                         Borough  Latitude Longitude
0  Barking and Dagenham [note 1]  ﻿51.5607    0.1557
1                         Barnet  ﻿51.6252    0.1517
2                         Bexley  ﻿51.4549    0.1505
3                          Brent  ﻿51.5588    0.2817
4                        Bromley  ﻿51.4039    0.0198

In [43]:
df3['Borough'] = df3['Borough'].str.split('[').str[0]
df3

C:\Users\Johnson\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

                    Borough  Latitude Longitude
0     Barking and Dagenham   ﻿51.5607    0.1557
1                    Barnet  ﻿51.6252    0.1517
2                    Bexley  ﻿51.4549    0.1505
3                     Brent  ﻿51.5588    0.2817
4                   Bromley  ﻿51.4039    0.0198
5                    Camden  ﻿51.5290    0.1255
6                   Croydon  ﻿51.3714    0.0977
7                    Ealing  ﻿51.5130    0.3089
8                   Enfield  ﻿51.6538    0.0799
9                Greenwich   ﻿51.4892    0.0648
10                  Hackney  ﻿51.5450    0.0553
11  Hammersmith and Fulham   ﻿51.4927    0.2339
12                 Haringey  ﻿51.6000    0.1119
13                   Harrow  ﻿51.5898    0.3346
14                 Havering  ﻿51.5812    0.1837
15               Hillingdon  ﻿51.5441    0.4760
16                 Hounslow  ﻿51.4746    0.3680
17                Islington  ﻿51.5416    0.1022
18   Kensington and Chelsea  ﻿51.5020    0.1947
19     Kingston upon Thames  ﻿51.4085    0.3064
20                  Lambeth  ﻿51.4607    0.1163
21                 Lewisham  ﻿51.4452    0.0209
22                   Merton  ﻿51.4014    0.1958
23                   Newham  ﻿51.5077    0.0469
24                Redbridge  ﻿51.5590    0.0741
25     Richmond upon Thames  ﻿51.4479    0.3260
26                Southwark  ﻿51.5035    0.0804
27                   Sutton  ﻿51.3618    0.1945
28            Tower Hamlets  ﻿51.5099    0.0059
29           Waltham Forest  ﻿51.5908    0.0134
30               Wandsworth  ﻿51.4567    0.1910
31              Westminster  ﻿51.4973    0.1372

In [44]:
df.columns = ['Code', 'Borough', 'Inner/_Outer_London',
       'GLA_Population_Estimate_2017', 'GLA_Household_Estimate_2017',
       'Inland_Area_(Hectares)', 'Population_density_(per_hectare)_2017',
       'Average_Age,_2017', 'Proportion_of_population_aged_0-15,_2015',
       'Proportion_of_population_of_working-age,_2015',
       'Proportion_of_population_aged_65_and_over,_2015',
       'Net_internal_migration_(2015)', 'Net_international_migration_(2015)',
       'Net_natural_change_(2015)',
       '%_of_resident_population_born_abroad_(2015)',
       'Largest_migrant_population_by_country_of_birth_(2011)',
       '%_of_largest_migrant_population_(2011)',
       'Second_largest_migrant_population_by_country_of_birth_(2011)',
       '%_of_second_largest_migrant_population_(2011)',
       'Third_largest_migrant_population_by_country_of_birth_(2011)',
       '%_of_third_largest_migrant_population_(2011)',
       '%_of_population_from_BAME_groups_(2016)',
       '%_people_aged_3+_whose_main_language_is_not_English_(2011_Census)',
       'Overseas_nationals_entering_the_UK_(NINo),_(2015/16)',
       'New_migrant_(NINo)_rates,_(2015/16)',
       'Largest_migrant_population_arrived_during_2015/16',
       'Second_largest_migrant_population_arrived_during_2015/16',
       'Third_largest_migrant_population_arrived_during_2015/16',
       'Employment_rate_(%)_(2015)', 'Male_employment_rate_(2015)',
       'Female_employment_rate_(2015)', 'Unemployment_rate_(2015)',
       'Youth_Unemployment_(claimant)_rate_18-24_(Dec-15)',
       'Proportion_of_16-18_year_olds_who_are_NEET_(%)_(2014)',
       'Proportion_of_the_working-age_population_who_claim_out-of-work_benefits_(%)_(May-2016)',
       '%_working-age_with_a_disability_(2015)',
       'Proportion_of_working_age_people_with_no_qualifications_(%)_2015',
       'Proportion_of_working_age_with_degree_or_equivalent_and_above_(%)_2015',
       'Gross_Annual_Pay,_(2016)', 'Gross_Annual_Pay_-_Male_(2016)',
       'Gross_Annual_Pay_-_Female_(2016)',
       'Modelled_Household_median_income_estimates_2012/13',
       '%_adults_that_volunteered_in_past_12_months_(2010/11_to_2012/13)',
       'Number_of_jobs_by_workplace_(2014)',
       '%_of_employment_that_is_in_public_sector_(2014)', 'Jobs_Density,_2015',
       'Number_of_active_businesses,_2015',
       'Two-year_business_survival_rates_(started_in_2013)',
       'Crime_rates_per_thousand_population_2014/15',
       'Fires_per_thousand_population_(2014)',
       'Ambulance_incidents_per_hundred_population_(2014)',
       'Median_House_Price,_2015',
       'Average_Band_D_Council_Tax_charge_(£),_2015/16',
       'New_Homes_(net)_2015/16_(provisional)',
       'Homes_Owned_outright,_(2014)_%',
       'Being_bought_with_mortgage_or_loan,_(2014)_%',
       'Rented_from_Local_Authority_or_Housing_Association,_(2014)_%',
       'Rented_from_Private_landlord,_(2014)_%',
       '%_of_area_that_is_Greenspace,_2005', 'Total_carbon_emissions_(2014)',
       'Household_Waste_Recycling_Rate,_2014/15',
       'Number_of_cars,_(2011_Census)',
       'Number_of_cars_per_household,_(2011_Census)',
       '%_of_adults_who_cycle_at_least_once_per_month,_2014/15',
       'Average_Public_Transport_Accessibility_score,_2014',
       'Achievement_of_5_or_more_A*-_C_grades_at_GCSE_or_equivalent_including_English_and_Maths,_2013/14',
       'Rates_of_Children_Looked_After_(2016)',
       '%_of_pupils_whose_first_language_is_not_English_(2015)',
       '%_children_living_in_out-of-work_households_(2015)',
       'Male_life_expectancy,_(2012-14)', 'Female_life_expectancy,_(2012-14)',
       'Teenage_conception_rate_(2014)',
       'Life_satisfaction_score_2011-14_(out_of_10)',
       'Worthwhileness_score_2011-14_(out_of_10)',
       'Happiness_score_2011-14_(out_of_10)',
       'Anxiety_score_2011-14_(out_of_10)',
       'Childhood_Obesity_Prevalance_(%)_2015/16',
       'People_aged_17+_with_diabetes_(%)',
       'Mortality_rate_from_causes_considered_preventable_2012/14',
       'Political_control_in_council',
       'Proportion_of_seats_won_by_Conservatives_in_2014_election',
       'Proportion_of_seats_won_by_Labour_in_2014_election',
       'Proportion_of_seats_won_by_Lib_Dems_in_2014_election',
       'Turnout_at_2014_local_elections']

df.head()

,Code,Borough,Inner/_Outer_London,GLA_Population_Estimate_2017,GLA_Household_Estimate_2017,Inland_Area_(Hectares),Population_density_(per_hectare)_2017,"Average_Age,_2017","Proportion_of_population_aged_0-15,_2015","Proportion_of_population_of_working-age,_2015","Proportion_of_population_aged_65_and_over,_2015",Net_internal_migration_(2015),Net_international_migration_(2015),Net_natural_change_(2015),%_of_resident_population_born_abroad_(2015),Largest_migrant_population_by_country_of_birth_(2011),%_of_largest_migrant_population_(2011),Second_largest_migrant_population_by_country_of_birth_(2011),%_of_second_largest_migrant_population_(2011),Third_largest_migrant_population_by_country_of_birth_(2011),%_of_third_largest_migrant_population_(2011),%_of_population_from_BAME_groups_(2016),%_people_aged_3+_whose_main_language_is_not_English_(2011_Census),"Overseas_nationals_entering_the_UK_(NINo),_(2015/16)","New_migrant_(NINo)_rates,_(2015/16)",Largest_migrant_population_arrived_during_2015/16,Second_largest_migrant_population_arrived_during_2015/16,Third_largest_migrant_population_arrived_during_2015/16,Employment_rate_(%)_(2015),Male_employment_rate_(2015),Female_employment_rate_(2015),Unemployment_rate_(2015),Youth_Unemployment_(claimant)_rate_18-24_(Dec-15),Proportion_of_16-18_year_olds_who_are_NEET_(%)_(2014),Proportion_of_the_working-age_population_who_claim_out-of-work_benefits_(%)_(May-2016),%_working-age_with_a_disability_(2015),Proportion_of_working_age_people_with_no_qualifications_(%)_2015,Proportion_of_working_age_with_degree_or_equivalent_and_above_(%)_2015,"Gross_Annual_Pay,_(2016)",Gross_Annual_Pay_-_Male_(2016),Gross_Annual_Pay_-_Female_(2016),Modelled_Household_median_income_estimates_2012/13,%_adults_that_volunteered_in_past_12_months_(2010/11_to_2012/13),Number_of_jobs_by_workplace_(2014),%_of_employment_that_is_in_public_sector_(2014),"Jobs_Density,_2015","Number_of_active_businesses,_2015",Two-year_business_survival_rates_(started_in_2013),Crime_rates_per_thousand_population_2014/15,Fires_per_thousand_population_(2014),Ambulance_incidents_per_hundred_population_(2014),"Median_House_Price,_2015","Average_Band_D_Council_Tax_charge_(£),_2015/16",New_Homes_(net)_2015/16_(provisional),"Homes_Owned_outright,_(2014)_%","Being_bought_with_mortgage_or_loan,_(2014)_%","Rented_from_Local_Authority_or_Housing_Association,_(2014)_%","Rented_from_Private_landlord,_(2014)_%","%_of_area_that_is_Greenspace,_2005",Total_carbon_emissions_(2014),"Household_Waste_Recycling_Rate,_2014/15","Number_of_cars,_(2011_Census)","Number_of_cars_per_household,_(2011_Census)","%_of_adults_who_cycle_at_least_once_per_month,_2014/15","Average_Public_Transport_Accessibility_score,_2014","Achievement_of_5_or_more_A*-_C_grades_at_GCSE_or_equivalent_including_English_and_Maths,_2013/14",Rates_of_Children_Looked_After_(2016),%_of_pupils_whose_first_language_is_not_English_(2015),%_children_living_in_out-of-work_households_(2015),"Male_life_expectancy,_(2012-14)","Female_life_expectancy,_(2012-14)",Teenage_conception_rate_(2014),Life_satisfaction_score_2011-14_(out_of_10),Worthwhileness_score_2011-14_(out_of_10),Happiness_score_2011-14_(out_of_10),Anxiety_score_2011-14_(out_of_10),Childhood_Obesity_Prevalance_(%)_2015/16,People_aged_17+_with_diabetes_(%),Mortality_rate_from_causes_considered_preventable_2012/14,Political_control_in_council,Proportion_of_seats_won_by_Conservatives_in_2014_election,Proportion_of_seats_won_by_Labour_in_2014_election,Proportion_of_seats_won_by_Lib_Dems_in_2014_election,Turnout_at_2014_local_elections
0,E09000001,City of London,Inner London,8800,5326,290,30.3,43.2,11.4,73.1,15.5,-7,665,30,.,United States,2.8,France,2,Australia,1.9,27.5,17.1,975,152.2,India,France,United States,64.6,.,.,.,1.6,.,3.4,.,.,.,.,.,.,"£63,620",.,500400,3.4,84.3,26130,64.3,.,12.3,.,799999,931.2,80,.,.,.,.,4.8,1036,34.4,1692,0.4,16.9,7.9,78.6,101,.,7.9,.,.,.,6.6,7.1,6.0,5.6,NaN,2.6,129,.,.,.,.,.
1,E09000002,Barking and Dagenham,Outer London,209000,78188,"3,611",57.9,32.9,27.2,63.1,9.7,-1176,2509,2356,37.8,Nigeria,4.7,India,2.3,Pakistan,2.3,49.5,18.7,"7,538",59.1,Romania,Bulgaria,Lithuania,65.8,75.6,56.5,11,4.5,5.7,10.5,17.2,11.3,32.2,27886,30104,24602,"£29,420",20.5,58900,21.1,0.5,6560,73.0,83.4,3,13.7,243500,1354.03,730,16.4,27.4,35.9,20.3,33.6,644,23.4,56966,0.8,8.8,3,58,69,41.7,18.7,77.6,82.1,32.4,7.1,7.6,7.1,3.1,28.5,7.3,228,Lab,0,100,0,36.5
2,E09000003,Barnet,Outer London,389600,151423,"8,675",44.9,37.3,21.1,64.9,14.0,-3379,5407,2757,35.2,India,3.1,Poland,2.4,Iran,2,38.7,23.4,"13,094",53.1,Romania,Poland,Italy,68.5,74.5,62.9,8.5,1.9,2.5,6.2,14.9,5.2,49,33443,36475,31235,"£40,530",33.2,167300,18.7,0.7,26190,73.8,62.7,1.6,11.1,445000,1397.07,1460,32.4,25.2,11.1,31.1,41.3,1415,38,144717,1.1,7.4,3,67.3,35,46,9.3,82.1,85.1,12.8,7.5,7.8,7.4,2.8,20.7,6.0,134,Cons,50.8,.,1.6,40.5
3,E09000004,Bexley,Outer London,244300,97736,"6,058",40.3,39.0,20.6,62.9,16.6,413,760,1095,16.1,Nigeria,2.6,India,1.5,Ireland,0.9,21.4,6,"2,198",14.4,Romania,Poland,Nigeria,75.1,82.1,68.5,7.6,2.9,3.4,6.8,15.9,10.8,33.5,34350,37881,28924,"£36,990",22.1,80700,15.9,0.6,9075,73.5,51.8,2.3,11.8,275000,1472.43,-130,38.1,35.3,15.2,11.4,31.7,975,54,108507,1.2,10.6,2.6,60.3,46,32.6,12.6,80.4,84.4,19.5,7.4,7.7,7.2,3.3,22.7,6.9,164,Cons,71.4,23.8,0,39.6
4,E09000005,Brent,Outer London,332100,121048,"4,323",76.8,35.6,20.9,67.8,11.3,-7739,7640,3372,53.9,India,9.2,Poland,3.4,Ireland,2.9,64.9,37.2,"22,162",100.9,Romania,Italy,Portugal,69.5,76,62.6,7.5,3.1,2.6,8.3,17.7,6.2,45.1,29812,30129,29600,"£32,140",17.3,133600,17.6,0.6,15745,74.4,78.8,1.8,12.1,407250,1377.24,1050,22.2,22.6,20.4,34.8,21.9,1175,35.2,87802,0.8,7.9,3.7,60.1,45,37.6,13.7,80.1,85.1,18.5,7.3,7.4,7.2,2.9,24.3,7.9,169,Lab,9.5,88.9,1.6,36.3

In [45]:
London = df.merge(df3, on='Borough')

In [46]:
London  = London[['Borough', 'Latitude', 'Longitude', 'Mortality_rate_from_causes_considered_preventable_2012/14', 'Median_House_Price,_2015', 'Crime_rates_per_thousand_population_2014/15', 'Number_of_active_businesses,_2015', 'Gross_Annual_Pay,_(2016)', 'Unemployment_rate_(2015)', 'Average_Age,_2017' ]]
London.head()

,Borough,Latitude,Longitude,Mortality_rate_from_causes_considered_preventable_2012/14,"Median_House_Price,_2015",Crime_rates_per_thousand_population_2014/15,"Number_of_active_businesses,_2015","Gross_Annual_Pay,_(2016)",Unemployment_rate_(2015),"Average_Age,_2017"
0,Barnet,﻿51.6252,0.1517,134,445000,62.7,26190,33443,8.5,37.3
1,Bexley,﻿51.4549,0.1505,164,275000,51.8,9075,34350,7.6,39.0
2,Brent,﻿51.5588,0.2817,169,407250,78.8,15745,29812,7.5,35.6
3,Bromley,﻿51.4039,0.0198,148,374975,64.1,15695,37682,5.3,40.2
4,Camden,﻿51.5290,0.1255,164,700000,123.5,31385,39796,4,36.4

#### Re-edit Column names

In [47]:
London.columns = ['Borough', 'Latitude', 'Longitude',
       'Mortality rate from preventable cause',
       'Median House Price',
       'Crime rates',
       'Active businesses', 'Gross Annual Pay',
       'Unemployment rate', 'Average Age']

London

,Borough,Latitude,Longitude,Mortality rate from preventable cause,Median House Price,Crime rates,Active businesses,Gross Annual Pay,Unemployment rate,Average Age
0,Barnet,﻿51.6252,0.1517,134,445000,62.7,26190,33443,8.5,37.3
1,Bexley,﻿51.4549,0.1505,164,275000,51.8,9075,34350,7.6,39.0
2,Brent,﻿51.5588,0.2817,169,407250,78.8,15745,29812,7.5,35.6
3,Bromley,﻿51.4039,0.0198,148,374975,64.1,15695,37682,5.3,40.2
4,Camden,﻿51.5290,0.1255,164,700000,123.5,31385,39796,4,36.4
5,Croydon,﻿51.3714,0.0977,178,300000,77,15540,32696,4.1,37.0
6,Ealing,﻿51.5130,0.3089,164,430000,75.5,18700,31331,5.8,36.2
7,Enfield,﻿51.6538,0.0799,152,320000,69.4,13925,31603,3.8,36.3
8,Hackney,﻿51.5450,0.0553,211,485000,99.6,18510,32056,5.9,33.1
9,Haringey,﻿51.6000,0.1119,183,432500,90.2,12675,31063,5.7,35.1
10,Harrow,﻿51.5898,0.3346,134,396150,50.4,15155,33202,4.6,38.3
11,Havering,﻿51.5812,0.1837,159,287500,62.9,10115,33398,5.3,40.3
12,Hillingdon,﻿51.5441,0.4760,170,350000,76.6,13505,33508,5.8,36.4
13,Hounslow,﻿51.4746,0.3680,166,355000,79.2,13910,31001,4.3,35.8
14,Islington,﻿51.5416,0.1022,203,583000,121.2,22110,36592,4.5,34.8
15,Kensington and Chelsea,﻿51.5020,0.1947,136,1200000,120.9,14350,.,4.2,39.3
16,Kingston upon Thames,﻿51.4085,0.3064,141,410000,58.5,8970,37979,4.5,37.1
17,Lambeth,﻿51.4607,0.1163,205,450000,104.6,17280,33441,5.9,34.5
18,Lewisham,﻿51.4452,0.0209,191,352000,77,10405,33157,5.7,35.0
19,Merton,﻿51.4014,0.1958,162,415000,59.7,12070,33989,4.6,36.7
20,Newham,﻿51.5077,0.0469,193,305000,90.8,11055,27942,9.1,32.1
21,Redbridge,﻿51.5590,0.0741,142,345000,69.7,14595,33483,7.9,35.8
22,Richmond upon Thames,﻿51.4479,0.3260,137,575000,56.3,14185,42076,3.8,38.8
23,Southwark,﻿51.5035,0.0804,207,475000,100.6,17120,33864,7.7,34.4
24,Sutton,﻿51.3618,0.1945,163,320000,55.9,8710,32697,5.5,38.9
25,Tower Hamlets,﻿51.5099,0.0059,239,415000,99.9,18390,36429,9.2,31.4
26,Waltham Forest,﻿51.5908,0.0134,185,366569,78,11020,30859,5.4,35.1
27,Wandsworth,﻿51.4567,0.1910,177,557000,72.6,18695,41064,5.7,35.0
28,Westminster,﻿51.4973,0.1372,162,920000,212.4,55385,42141,8.8,37.7

In [48]:
London['Latitude'] = London['Latitude'].astype(str)
London['Latitude']= London['Latitude'].str.split('﻿').str[1]
London

,Borough,Latitude,Longitude,Mortality rate from preventable cause,Median House Price,Crime rates,Active businesses,Gross Annual Pay,Unemployment rate,Average Age
0,Barnet,51.6252,0.1517,134,445000,62.7,26190,33443,8.5,37.3
1,Bexley,51.4549,0.1505,164,275000,51.8,9075,34350,7.6,39.0
2,Brent,51.5588,0.2817,169,407250,78.8,15745,29812,7.5,35.6
3,Bromley,51.4039,0.0198,148,374975,64.1,15695,37682,5.3,40.2
4,Camden,51.5290,0.1255,164,700000,123.5,31385,39796,4,36.4
5,Croydon,51.3714,0.0977,178,300000,77,15540,32696,4.1,37.0
6,Ealing,51.5130,0.3089,164,430000,75.5,18700,31331,5.8,36.2
7,Enfield,51.6538,0.0799,152,320000,69.4,13925,31603,3.8,36.3
8,Hackney,51.5450,0.0553,211,485000,99.6,18510,32056,5.9,33.1
9,Haringey,51.6000,0.1119,183,432500,90.2,12675,31063,5.7,35.1
10,Harrow,51.5898,0.3346,134,396150,50.4,15155,33202,4.6,38.3
11,Havering,51.5812,0.1837,159,287500,62.9,10115,33398,5.3,40.3
12,Hillingdon,51.5441,0.4760,170,350000,76.6,13505,33508,5.8,36.4
13,Hounslow,51.4746,0.3680,166,355000,79.2,13910,31001,4.3,35.8
14,Islington,51.5416,0.1022,203,583000,121.2,22110,36592,4.5,34.8
15,Kensington and Chelsea,51.5020,0.1947,136,1200000,120.9,14350,.,4.2,39.3
16,Kingston upon Thames,51.4085,0.3064,141,410000,58.5,8970,37979,4.5,37.1
17,Lambeth,51.4607,0.1163,205,450000,104.6,17280,33441,5.9,34.5
18,Lewisham,51.4452,0.0209,191,352000,77,10405,33157,5.7,35.0
19,Merton,51.4014,0.1958,162,415000,59.7,12070,33989,4.6,36.7
20,Newham,51.5077,0.0469,193,305000,90.8,11055,27942,9.1,32.1
21,Redbridge,51.5590,0.0741,142,345000,69.7,14595,33483,7.9,35.8
22,Richmond upon Thames,51.4479,0.3260,137,575000,56.3,14185,42076,3.8,38.8
23,Southwark,51.5035,0.0804,207,475000,100.6,17120,33864,7.7,34.4
24,Sutton,51.3618,0.1945,163,320000,55.9,8710,32697,5.5,38.9
25,Tower Hamlets,51.5099,0.0059,239,415000,99.9,18390,36429,9.2,31.4
26,Waltham Forest,51.5908,0.0134,185,366569,78,11020,30859,5.4,35.1
27,Wandsworth,51.4567,0.1910,177,557000,72.6,18695,41064,5.7,35.0
28,Westminster,51.4973,0.1372,162,920000,212.4,55385,42141,8.8,37.7

In [49]:
London['Longitude'] = '-' + London['Longitude'].astype(str)

In [50]:
London['Longitude']

0     -0.1517
1     -0.1505
2     -0.2817
3     -0.0198
4     -0.1255
5     -0.0977
6     -0.3089
7     -0.0799
8     -0.0553
9     -0.1119
10    -0.3346
11    -0.1837
12    -0.4760
13    -0.3680
14    -0.1022
15    -0.1947
16    -0.3064
17    -0.1163
18    -0.0209
19    -0.1958
20    -0.0469
21    -0.0741
22    -0.3260
23    -0.0804
24    -0.1945
25    -0.0059
26    -0.0134
27    -0.1910
28    -0.1372
Name: Longitude, dtype: object

In [51]:
London.head()

,Borough,Latitude,Longitude,Mortality rate from preventable cause,Median House Price,Crime rates,Active businesses,Gross Annual Pay,Unemployment rate,Average Age
0,Barnet,51.6252,-0.1517,134,445000,62.7,26190,33443,8.5,37.3
1,Bexley,51.4549,-0.1505,164,275000,51.8,9075,34350,7.6,39.0
2,Brent,51.5588,-0.2817,169,407250,78.8,15745,29812,7.5,35.6
3,Bromley,51.4039,-0.0198,148,374975,64.1,15695,37682,5.3,40.2
4,Camden,51.5290,-0.1255,164,700000,123.5,31385,39796,4,36.4

## Explore Neighbourhood in London & preparing Data for Clustering

In [52]:
nearby_venues.columns = ['name', 'categories', 'Latitude', 'Longitude']
nearby_venues

,name,categories,Latitude,Longitude
0,National Gallery,Art Museum,51.508876,-0.128478
1,Trafalgar Square,Plaza,51.507987,-0.128048
2,East Trafalgar Square Fountain,Fountain,51.508088,-0.127700
3,Sainsbury Wing National Gallery,Art Museum,51.508384,-0.129001
4,Trafalgar Square Lions,Outdoor Sculpture,51.507641,-0.127888
5,ESPA Life at Corinthia,Spa,51.506402,-0.125114
6,St Martin-in-the-Fields,Church,51.508746,-0.126507
7,Nelson's Column,Monument / Landmark,51.507744,-0.127931
8,Corinthia Hotel,Hotel,51.506607,-0.124460
9,National Portrait Gallery,Art Gallery,51.509438,-0.128032
10,Trafalgar Studios,Theater,51.506651,-0.127378
11,Waterstones,Bookstore,51.507650,-0.127130
12,George Washington Statue,Outdoor Sculpture,51.508659,-0.127705
13,Institute of Contemporary Arts (ICA),Art Gallery,51.506265,-0.130817
14,Barrafina,Spanish Restaurant,51.509427,-0.125894
15,Afternoon Tea at the Corinthia Hotel,Tea Room,51.506572,-0.124350
16,Haymarket Hotel,Hotel,51.508267,-0.131315
17,Tandoor Chop House,North Indian Restaurant,51.509192,-0.125638
18,Bancone,Italian Restaurant,51.509529,-0.126434
19,Minamoto Kitchoan,Candy Store,51.508652,-0.125480
20,Kerridge’s Bar & Grill,Restaurant,51.506728,-0.124520
21,Horse Guards Parade,Plaza,51.504847,-0.126590
22,Thai Square,Thai Restaurant,51.507656,-0.129830
23,English National Opera,Opera House,51.509804,-0.126945
24,The London Coliseum,Theater,51.509846,-0.127005
25,Café In The Crypt,Café,51.508962,-0.126729
26,The Admiralty,Pub,51.507303,-0.128847
27,The Harp,Pub,51.509719,-0.125943
28,Gordon's Wine Bar,Wine Bar,51.507911,-0.123293
29,Her Majesty's Theatre,Theater,51.508289,-0.131641
30,ICA Cinema,Indie Movie Theater,51.506018,-0.131068
31,The Royal Horseguards,Hotel,51.506127,-0.124224
32,Terroirs,Wine Bar,51.509547,-0.125250
33,National Portrait Gallery Shop,Gift Shop,51.509356,-0.127373
34,Nutshell,Persian Restaurant,51.509632,-0.126605
35,Pret A Manger,Sandwich Place,51.508114,-0.129910
36,Notes Music & Coffee,Coffee Shop,51.509696,-0.126985
37,Sofitel London St James,Hotel,51.507636,-0.132367
38,Mall Galleries,Art Gallery,51.506370,-0.129776
39,Whitehall Gardens,Garden,51.506354,-0.122900
40,Five Guys,Burger Joint,51.508520,-0.124363
41,Amorino,Ice Cream Shop,51.510427,-0.128401
42,Dover Street Market,Boutique,51.508981,-0.131867
43,The Household Cavalry Museum,History Museum,51.504869,-0.126594
44,MOD Pizza,Pizza Place,51.510011,-0.129131
45,Brumus,French Restaurant,51.508198,-0.131485
46,The Northall,English Restaurant,51.506599,-0.123821
47,Japan Centre,Japanese Restaurant,51.509761,-0.131273
48,St. Martin's Lane Hotel,Hotel,51.510526,-0.126705
49,Leicester Square Garden,Garden,51.510361,-0.130127
50,Ole & Steen,Bakery,51.509219,-0.132597
51,Wahaca,Mexican Restaurant,51.510221,-0.124524
52,The Whisky Exchange,Liquor Store,51.509974,-0.123713
53,The London Beer House,Bar,51.508214,-0.132578
54,Victoria Embankment Gardens,Park,51.508135,-0.122079
55,Steak & Co.,Steakhouse,51.509923,-0.128494
56,Harold Pinter Theatre,Theater,51.509443,-0.131644
57,hub by Premier Inn London Covent Garden,Hotel,51.510036,-0.127111
58,Milos,Greek Restaurant,51.508117,-0.133341
59,Mr Fogg's Society of Exploration,Cocktail Bar,51.509769,-0.123532
60,Kanada-Ya,Ramen Restaurant,51.509359,-0.132215
61,Retro Bar,Gay Bar,51.509153,-0.123533
62,Leicester Square,Plaza,51.510519,-0.130098
63,Prince of Wales Theatre,Theater,51.510132,-0.131594
64,The LEGO Store,Toy / Game Store,51.510497,-0.131001
65,Superdrug,Pharmacy,51.509174,-0.124054
66,J Sheekey,Seafood Restaurant,51.510899,-0.127797
67,La Gelatiera,Ice Cream Shop,51.511046,-0.126828
68,Noel Coward Theatre,Theater,51.511042,-0.127619
69,Sandwich Centre,Sandwich Place,51.508174,-0.132451
70,St James Bar,Cocktail Bar,51.507442,-0.132402
71,Scully,Restaurant,51.508744,-0.133083
72,Gymbox,Gym / Fitness Center,51.510468,-0.126803
73,So Spa,Spa,51.507601,-0.132690
74,Lao Café,Asian Restaurant,51.509987,-0.124891
75,Mr Fogg's Tavern,Pub,51.511000,-0.126952
76,Rochelle Canteen at ICA,English Restaurant,51.506258,-0.130640
77,Guards Memorial,Monument / Landmark,51.504595,-0.129438
78,Machiya,Japanese Restaurant,51.509413,-0.131994
79,Flat Iron,Steakhouse,51.510841,-0.124093
80,The Alchemist,Cocktail Bar,51.511458,-0.126955
81,The Z Hotel Piccadilly,Hotel,51.509009,-0.131564
82,Nando's,Portuguese Restaurant,51.510325,-0.124604
83,The Espresso Room,Coffee Shop,51.511074,-0.126568
84,Adelphi Theatre,Theater,51.510383,-0.123068
85,Mr Fogg's Gin Parlour,Speakeasy,51.511012,-0.126945
86,WA Cafe,Café,51.511009,-0.126614
87,Simit Sarayı,Bagel Shop,51.510597,-0.130643
88,Amorino,Ice Cream Shop,51.511510,-0.125794
89,Blame Gloria,Bar,51.510905,-0.124615
90,The Royal Trafalgar by Thistle,Hotel,51.509087,-0.130328
91,Byron,Burger Joint,51.508871,-0.131699
92,The Original London Sightseeing Tour,Tour Provider,51.508011,-0.130052
93,The Comedy Store,Comedy Club,51.510234,-0.132507
94,Imperial Treasure Fine Chinese Cuisine,Chinese Restaurant,51.507935,-0.132977
95,M&M's World,Candy Store,51.510599,-0.131149
96,Wyndham's Theatre,Theater,51.511072,-0.127990
97,Busaba Eathai,Thai Restaurant,51.509987,-0.131019
98,Sticks'n'Sushi,Sushi Restaurant,51.511038,-0.123655
99,The Port House,Wine Bar,51.509893,-0.123001

In [53]:
London['Latitude'] = London['Latitude'].astype(float)

In [54]:
London['Longitude']=London['Longitude'].astype(float)

In [58]:
def getNearbyVenues(names, latitudes, longitudes, radius=500):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Borough', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

In [59]:
London_venues = getNearbyVenues(names=London['Borough'],
                                   latitudes=London['Latitude'],
                                   longitudes=London['Longitude']
                                  )

Barnet
Bexley
Brent
Bromley
Camden
Croydon
Ealing
Enfield
Hackney
Haringey
Harrow
Havering
Hillingdon
Hounslow
Islington
Kensington and Chelsea
Kingston upon Thames
Lambeth
Lewisham
Merton
Newham
Redbridge
Richmond upon Thames
Southwark
Sutton
Tower Hamlets
Waltham Forest
Wandsworth
Westminster

In [60]:
print(London_venues.shape)
London_venues.head()

(1290, 7)

,Borough,Neighborhood Latitude,Neighborhood Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
0,Barnet,51.6252,-0.1517,The Atrium,51.624726,-0.151933,Café
1,Barnet,51.6252,-0.1517,JusDrive LTD,51.625563,-0.151963,Rental Car Location
2,Barnet,51.6252,-0.1517,Beaconsfield Road (BF),51.622827,-0.151466,Bus Stop
3,Barnet,51.6252,-0.1517,Oakleigh Cafe,51.623412,-0.154899,Café
4,Barnet,51.6252,-0.1517,LGA Properties Ltd,51.625005,-0.156671,Construction & Landscaping

In [62]:
# one hot encoding
London_one = pd.get_dummies(London_venues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
London_one['Borough'] = London_venues['Borough'] 

# move neighborhood column to the first column
fixed_columns = [London_one.columns[-1]] + list(London_one.columns[:-1])
London_one = London_one[fixed_columns]

London_one.head()

,Borough,African Restaurant,American Restaurant,Argentinian Restaurant,Art Gallery,Art Museum,Arts & Crafts Store,Asian Restaurant,Australian Restaurant,BBQ Joint,Bakery,Bar,Bed & Breakfast,Beer Bar,Beer Garden,Beer Store,Bistro,Bookstore,Boutique,Brazilian Restaurant,Breakfast Spot,Brewery,Bubble Tea Shop,Buffet,Burger Joint,Burrito Place,Bus Station,Bus Stop,Butcher,Café,Cajun / Creole Restaurant,Camera Store,Candy Store,Cantonese Restaurant,Caribbean Restaurant,Caucasian Restaurant,Chaat Place,Champagne Bar,Chinese Restaurant,Chocolate Shop,Church,Clothing Store,Cocktail Bar,Coffee Shop,Concert Hall,Construction & Landscaping,Convenience Store,Cosmetics Shop,Creperie,Cupcake Shop,Dance Studio,Deli / Bodega,Department Store,Dessert Shop,Dim Sum Restaurant,Diner,Discount Store,Donut Shop,Dumpling Restaurant,Electronics Store,English Restaurant,Event Space,Falafel Restaurant,Farmers Market,Fast Food Restaurant,Film Studio,Fish & Chips Shop,Fish Market,Food Court,Forest,French Restaurant,Fried Chicken Joint,Frozen Yogurt Shop,Fruit & Vegetable Store,Furniture / Home Store,Gaming Cafe,Garden,Garden Center,Gastropub,German Restaurant,Gift Shop,Greek Restaurant,Grocery Store,Gym,Gym / Fitness Center,Hardware Store,Health Food Store,Historic Site,History Museum,Hobby Shop,Hookah Bar,Hostel,Hotel,Hotel Bar,Ice Cream Shop,Indian Restaurant,Indie Movie Theater,Irish Pub,Italian Restaurant,Japanese Restaurant,Jazz Club,Jewelry Store,Juice Bar,Kebab Restaurant,Kitchen Supply Store,Korean Restaurant,Latin American Restaurant,Lebanese Restaurant,Light Rail Station,Lighting Store,Liquor Store,Lounge,Malay Restaurant,Market,Mediterranean Restaurant,Metro Station,Mexican Restaurant,Middle Eastern Restaurant,Mobile Phone Shop,Modern European Restaurant,Movie Theater,Multiplex,Museum,Music Store,Music Venue,New American Restaurant,Nightclub,Okonomiyaki Restaurant,Optical Shop,Organic Grocery,Outdoor Event Space,Outdoor Sculpture,Outdoor Supply Store,Outlet Mall,Outlet Store,Paper / Office Supplies Store,Park,Pedestrian Plaza,Performing Arts Venue,Persian Restaurant,Pharmacy,Pier,Pizza Place,Platform,Playground,Plaza,Polish Restaurant,Pool,Pool Hall,Portuguese Restaurant,Pub,Public Art,Ramen Restaurant,Record Shop,Recording Studio,Rental Car Location,Restaurant,Road,Roof Deck,Salad Place,Sandwich Place,Scandinavian Restaurant,Scenic Lookout,Seafood Restaurant,Shoe Store,Shopping Mall,Shopping Plaza,Smoothie Shop,South American Restaurant,South Indian Restaurant,Southern / Soul Food Restaurant,Souvenir Shop,Spa,Spanish Restaurant,Speakeasy,Sporting Goods Shop,Sports Bar,Stadium,Stationery Store,Steakhouse,Street Art,Street Food Gathering,Supermarket,Sushi Restaurant,Tapas Restaurant,Tea Room,Tennis Court,Thai Restaurant,Theater,Thrift / Vintage Store,Tiki Bar,Toy / Game Store,Train Station,Turkish Restaurant,Used Bookstore,Vegetarian / Vegan Restaurant,Video Game Store,Vietnamese Restaurant,Warehouse Store,Wine Bar,Wine Shop,Winery,Women's Store,Yoga Studio
0,Barnet,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Barnet,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,Barnet,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Barnet,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,Barnet,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [63]:
London_grouped = London_one.groupby('Borough').mean().reset_index()
London_grouped.head()

,Borough,African Restaurant,American Restaurant,Argentinian Restaurant,Art Gallery,Art Museum,Arts & Crafts Store,Asian Restaurant,Australian Restaurant,BBQ Joint,Bakery,Bar,Bed & Breakfast,Beer Bar,Beer Garden,Beer Store,Bistro,Bookstore,Boutique,Brazilian Restaurant,Breakfast Spot,Brewery,Bubble Tea Shop,Buffet,Burger Joint,Burrito Place,Bus Station,Bus Stop,Butcher,Café,Cajun / Creole Restaurant,Camera Store,Candy Store,Cantonese Restaurant,Caribbean Restaurant,Caucasian Restaurant,Chaat Place,Champagne Bar,Chinese Restaurant,Chocolate Shop,Church,Clothing Store,Cocktail Bar,Coffee Shop,Concert Hall,Construction & Landscaping,Convenience Store,Cosmetics Shop,Creperie,Cupcake Shop,Dance Studio,Deli / Bodega,Department Store,Dessert Shop,Dim Sum Restaurant,Diner,Discount Store,Donut Shop,Dumpling Restaurant,Electronics Store,English Restaurant,Event Space,Falafel Restaurant,Farmers Market,Fast Food Restaurant,Film Studio,Fish & Chips Shop,Fish Market,Food Court,Forest,French Restaurant,Fried Chicken Joint,Frozen Yogurt Shop,Fruit & Vegetable Store,Furniture / Home Store,Gaming Cafe,Garden,Garden Center,Gastropub,German Restaurant,Gift Shop,Greek Restaurant,Grocery Store,Gym,Gym / Fitness Center,Hardware Store,Health Food Store,Historic Site,History Museum,Hobby Shop,Hookah Bar,Hostel,Hotel,Hotel Bar,Ice Cream Shop,Indian Restaurant,Indie Movie Theater,Irish Pub,Italian Restaurant,Japanese Restaurant,Jazz Club,Jewelry Store,Juice Bar,Kebab Restaurant,Kitchen Supply Store,Korean Restaurant,Latin American Restaurant,Lebanese Restaurant,Light Rail Station,Lighting Store,Liquor Store,Lounge,Malay Restaurant,Market,Mediterranean Restaurant,Metro Station,Mexican Restaurant,Middle Eastern Restaurant,Mobile Phone Shop,Modern European Restaurant,Movie Theater,Multiplex,Museum,Music Store,Music Venue,New American Restaurant,Nightclub,Okonomiyaki Restaurant,Optical Shop,Organic Grocery,Outdoor Event Space,Outdoor Sculpture,Outdoor Supply Store,Outlet Mall,Outlet Store,Paper / Office Supplies Store,Park,Pedestrian Plaza,Performing Arts Venue,Persian Restaurant,Pharmacy,Pier,Pizza Place,Platform,Playground,Plaza,Polish Restaurant,Pool,Pool Hall,Portuguese Restaurant,Pub,Public Art,Ramen Restaurant,Record Shop,Recording Studio,Rental Car Location,Restaurant,Road,Roof Deck,Salad Place,Sandwich Place,Scandinavian Restaurant,Scenic Lookout,Seafood Restaurant,Shoe Store,Shopping Mall,Shopping Plaza,Smoothie Shop,South American Restaurant,South Indian Restaurant,Southern / Soul Food Restaurant,Souvenir Shop,Spa,Spanish Restaurant,Speakeasy,Sporting Goods Shop,Sports Bar,Stadium,Stationery Store,Steakhouse,Street Art,Street Food Gathering,Supermarket,Sushi Restaurant,Tapas Restaurant,Tea Room,Tennis Court,Thai Restaurant,Theater,Thrift / Vintage Store,Tiki Bar,Toy / Game Store,Train Station,Turkish Restaurant,Used Bookstore,Vegetarian / Vegan Restaurant,Video Game Store,Vietnamese Restaurant,Warehouse Store,Wine Bar,Wine Shop,Winery,Women's Store,Yoga Studio
0,Barnet,0.0,0.000000,0.0,0.00,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.00,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.2,0.0,0.400000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.00,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.2,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.000000,0.00,0.0,0.00,0.0,0.000000,0.00,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.00,0.0,0.00,0.0,0.00,0.00,0.000000,0.0,0.000000,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.00,0.00,0.0,0.000000,0.000000,0.0,0.0,0.00,0.0,0.000000,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.00,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.00,0.00,0.000000,0.0,0.0,0.0,0.00,0.2,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.000000,0.000000,0.000000,0.00,0.0,0.0,0.0,0.000000,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.000000,0.0,0.0,0.0
1,Bexley,0.0,0.000000,0.0,0.00,0.0,0.0,0.000000,0.0,0.0,0.000000,0.047619,0.0,0.0,0.0,0.0,0.000000,0.00,0.0,0.000000,0.047619,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.047619,0.0,0.00,0.0,0.000000,0.0,0.000000,0.0,0.047619,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.000000,0.00,0.0,0.00,0.0,0.047619,0.00,0.047619,0.047619,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.00,0.0,0.00,0.0,0.00,0.00,0.095238,0.0,0.000000,0.0,0.00,0.047619,0.0,0.0,0.0,0.0,0.047619,0.000000,0.000000,0.047619,0.0,0.0,0.047619,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.00,0.00,0.0,0.047619,0.047619,0.0,0.0,0.00,0.0,0.000000,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.047619,0.000000,0.0,0.0,0.00,0.0,0.047619,0.0,0.0,0.047619,0.0,0.0,0.00,0.00,0.047619,0.0,0.0,0.0,0.00,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.000000,0.000000,0.000000,0.00,0.0,0.0,0.0,0.047619,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.047619,0.0,0.0,0.0
2,Brent,0.0,0.025974,0.0,0.00,0.0,0.0,0.012987,0.0,0.0,0.012987,0.064935,0.0,0.0,0.0,0.0,0.012987,0.00,0.0,0.012987,0.000000,0.0,0.012987,0.012987,0.025974,0.0,0.0,0.0,0.0,0.012987,0.0,0.0,0.012987,0.0,0.0,0.000000,0.0,0.00,0.0,0.012987,0.0,0.064935,0.0,0.103896,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.012987,0.0,0.0,0.0,0.012987,0.00,0.0,0.00,0.0,0.012987,0.00,0.000000,0.000000,0.012987,0.0,0.0,0.0,0.0,0.0,0.012987,0.0,0.00,0.0,0.00,0.0,0.00,0.00,0.038961,0.0,0.012987,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.090909,0.012987,0.012987,0.025974,0.0,0.0,0.025974,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.012987,0.0,0.0,0.0,0.0,0.012987,0.00,0.00,0.0,0.000000,0.000000,0.0,0.0,0.00,0.0,0.012987,0.00,0.0,0.012987,0.0,0.0,0.0,0.0,0.0,0.0,0.012987,0.0,0.012987,0.012987,0.0,0.000000,0.012987,0.0,0.0,0.00,0.0,0.012987,0.0,0.0,0.012987,0.0,0.0,0.00,0.00,0.000000,0.0,0.0,0.0,0.00,0.0,0.012987,0.0,0.012987,0.0,0.038961,0.0,0.0,0.012987,0.012987,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.051948,0.012987,0.012987,0.00,0.0,0.0,0.0,0.012987,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.000000,0.0,0.0,0.0
3,Bromley,0.0,0.000000,0.0,0.00,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.00,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.400000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.00,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.000000,0.00,0.0,0.00,0.0,0.000000,0.00,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.00,0.0,0.20,0.0,0.00,0.00,0.000000,0.0,0.000000,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.00,0.00,0.0,0.000000,0.000000,0.0,0.0,0.00,0.0,0.000000,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.200000,0.000000,0.0,0.0,0.00,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.00,0.00,0.200000,0.0,0.0,0.0,0.00,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.000000,0.000000,0.000000,0.00,0.0,0.0,0.0,0.000000,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.000000,0.0,0.0,0.0
4,Camden,0.0,0.000000,0.0,0.01,0.0,0.0,0.000000,0.0,0.0,0.020000,0.010000,0.0,0.0,0.0,0.0,0.000000,0.01,0.0,0.000000,0.020000,0.0,0.000000,0.000000,0.040000,0.0,0.0,0.0,0.0,0.060000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.01,0.0,0.010000,0.0,0.000000,0.0,0.080000,0.0,0.0,0.0,0.0,0.0,0.0,0.01,0.02,0.0,0.01,0.0,0.000000,0.0,0.0,0.0,0.000000,0.01,0.0,0.01,0.0,0.000000,0.01,0.010000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.02,0.0,0.01,0.0,0.01,0.01,0.010000,0.0,0.010000,0.0,0.01,0.000000,0.0,0.0,0.0,0.0,0.080000,0.020000,0.000000,0.010000,0.0,0.0,0.030000,0.0,0.0,0.0,0.01,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.01,0.01,0.0,0.000000,0.010000,0.0,0.0,0.02,0.0,0.000000,0.01,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.010000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.01,0.0,0.020000,0.0,0.0,0.020000,0.0,0.0,0.01,0.01,0.080000,0.0,0.0,0.0,0.01,0.0,0.020000,0.0,0.000000,0.0,0.040000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.01,0.0,0.0,0.01,0.010000,0.000000,0.000000,0.01,0.0,0.0,0.0,0.010000,0.01,0.01,0.0,0.0,0.01,0.0,0.0,0.0,0.0,0.02,0.01,0.01,0.0,0.0,0.0,0.0,0.01,0.000000,0.0,0.0,0.0

In [64]:
num_top_venues = 5

for hood in London_grouped['Borough']:
    print("----"+hood+"----")
    temp = London_grouped[London_grouped['Borough'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

----Barnet----
                        venue  freq
0                        Café   0.4
1                    Bus Stop   0.2
2  Construction & Landscaping   0.2
3         Rental Car Location   0.2
4          Light Rail Station   0.0


----Bexley----
           venue  freq
0  Grocery Store  0.10
1            Pub  0.05
2    Supermarket  0.05
3    Coffee Shop  0.05
4    Pizza Place  0.05


----Brent----
                 venue  freq
0          Coffee Shop  0.10
1                Hotel  0.09
2                  Bar  0.06
3       Clothing Store  0.06
4  Sporting Goods Shop  0.05


----Bromley----
       venue  freq
0       Café   0.4
1  Gastropub   0.2
2        Pub   0.2
3       Park   0.2
4   Pharmacy   0.0


----Camden----
          venue  freq
0           Pub  0.08
1   Coffee Shop  0.08
2         Hotel  0.08
3          Café  0.06
4  Burger Joint  0.04


----Croydon----
                   venue  freq
0                    Pub  0.12
1            Coffee Shop  0.10
2  Portuguese Restaurant  0.05
3            Supermarket  0.05
4          Burrito Place  0.02


----Ealing----
            venue  freq
0     Coffee Shop  0.11
1  Clothing Store  0.05
2             Pub  0.04
3            Park  0.04
4          Bakery  0.04


----Enfield----
              venue  freq
0       Coffee Shop  0.09
1    Clothing Store  0.08
2              Café  0.06
3      Optical Shop  0.04
4  Department Store  0.04


----Hackney----
          venue  freq
0           Pub  0.08
1          Café  0.07
2        Bakery  0.05
3   Coffee Shop  0.05
4  Cocktail Bar  0.05


----Haringey----
                   venue  freq
0   Fast Food Restaurant  0.10
1                   Café  0.05
2      Indian Restaurant  0.05
3  Portuguese Restaurant  0.05
4     Light Rail Station  0.05


----Harrow----
                 venue  freq
0    Indian Restaurant  0.25
1          Coffee Shop  0.25
2             Platform  0.12
3          Supermarket  0.12
4  Indie Movie Theater  0.12


----Havering----
                venue  freq
0                Park  0.50
1      Breakfast Spot  0.25
2              Forest  0.25
3  African Restaurant  0.00
4     Organic Grocery  0.00


----Hillingdon----
                  venue  freq
0           Coffee Shop  0.14
1        Clothing Store  0.10
2    Italian Restaurant  0.07
3  Fast Food Restaurant  0.05
4             Bookstore  0.03


----Hounslow----
             venue  freq
0      Pizza Place  0.25
1  Bed & Breakfast  0.25
2             Park  0.25
3             Café  0.25
4              Pub  0.00


----Islington----
                      venue  freq
0                       Pub  0.14
1  Mediterranean Restaurant  0.08
2              Cocktail Bar  0.05
3               Music Venue  0.03
4    Furniture / Home Store  0.03


----Kensington and Chelsea----
            venue  freq
0            Café  0.08
1  Clothing Store  0.05
2      Restaurant  0.05
3          Bakery  0.05
4       Juice Bar  0.03


----Kingston upon Thames----
                venue  freq
0         Coffee Shop  0.08
1                Café  0.07
2      Clothing Store  0.06
3                 Pub  0.05
4  Italian Restaurant  0.05


----Lambeth----
                  venue  freq
0  Caribbean Restaurant  0.05
1                Market  0.04
2                   Pub  0.04
3           Coffee Shop  0.04
4    Mexican Restaurant  0.04


----Lewisham----
           venue  freq
0    Supermarket  0.12
1  Grocery Store  0.09
2            Pub  0.06
3       Platform  0.06
4  Train Station  0.06


----Merton----
                venue  freq
0                Café  0.11
1         Supermarket  0.11
2                Park  0.11
3  Italian Restaurant  0.06
4       Garden Center  0.06


----Newham----
                venue  freq
0                 Pub  0.29
1            Bus Stop  0.14
2  Italian Restaurant  0.14
3                Park  0.14
4               Hotel  0.14


----Redbridge----
          venue  freq
0           Pub  0.15
1          Café  0.13
2  Cocktail Bar  0.08
3   Pizza Place  0.04
4           Bar  0.04


----Richmond upon Thames----
                venue  freq
0                 Pub  0.16
1         Coffee Shop  0.14
2  Italian Restaurant  0.10
3   Indian Restaurant  0.04
4       Grocery Store  0.04


----Southwark----
            venue  freq
0     Coffee Shop  0.11
1             Pub  0.06
2      Restaurant  0.05
3             Bar  0.05
4  Scenic Lookout  0.04


----Sutton----
                venue  freq
0                 Pub  0.14
1      Clothing Store  0.14
2         Coffee Shop  0.09
3  Italian Restaurant  0.06
4                Café  0.06


----Tower Hamlets----
                venue  freq
0               Hotel  0.13
1         Coffee Shop  0.13
2  Italian Restaurant  0.13
3   Convenience Store  0.07
4                Café  0.07


----Waltham Forest----
          venue  freq
0           Pub  0.18
1  Concert Hall  0.09
2   Coffee Shop  0.09
3   Art Gallery  0.09
4      Tea Room  0.09


----Wandsworth----
              venue  freq
0    Clothing Store  0.10
1               Pub  0.10
2       Coffee Shop  0.10
3  Asian Restaurant  0.05
4    Breakfast Spot  0.05


----Westminster----
            venue  freq
0     Coffee Shop  0.13
1           Hotel  0.12
2  Sandwich Place  0.09
3         Theater  0.05
4             Pub  0.05

In [65]:
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

In [75]:
num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Borough']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
London_venues_sorted = pd.DataFrame(columns=columns)
London_venues_sorted['Borough'] = London_grouped['Borough']

for ind in np.arange(London_grouped.shape[0]):
    London_venues_sorted.iloc[ind, 1:] = return_most_common_venues(London_grouped.iloc[ind, :], num_top_venues)

London_venues_sorted.head()

,Borough,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,Barnet,Café,Rental Car Location,Construction & Landscaping,Bus Stop,Yoga Studio,Film Studio,Fruit & Vegetable Store,Frozen Yogurt Shop,Fried Chicken Joint,French Restaurant
1,Bexley,Grocery Store,Pub,Fish & Chips Shop,Caucasian Restaurant,Coffee Shop,Plaza,Pizza Place,Park,Fast Food Restaurant,Fish Market
2,Brent,Coffee Shop,Hotel,Clothing Store,Bar,Sporting Goods Shop,Grocery Store,Sandwich Place,Italian Restaurant,Burger Joint,Indian Restaurant
3,Bromley,Café,Pub,Gastropub,Park,Furniture / Home Store,Frozen Yogurt Shop,Fried Chicken Joint,French Restaurant,Forest,Food Court
4,Camden,Pub,Hotel,Coffee Shop,Café,Sandwich Place,Burger Joint,Italian Restaurant,Bakery,Restaurant,Breakfast Spot

## K- Clustering

In [76]:
# set number of clusters
kclusters = 5

London_grouped_clustering = London_grouped.drop('Borough', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(London_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10]

array([4, 0, 0, 3, 0, 0, 0, 0, 0, 0])

In [77]:
# add clustering labels
London_venues_sorted.insert(0, 'Cluster_Labels', kmeans.labels_)

London_merged = London

London_merged = London_merged.join(London_venues_sorted.set_index('Borough'), on='Borough')

London_merged.head() # check the last columns!

,Borough,Latitude,Longitude,Mortality rate from preventable cause,Median House Price,Crime rates,Active businesses,Gross Annual Pay,Unemployment rate,Average Age,Cluster_Labels,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,Barnet,51.6252,-0.1517,134,445000,62.7,26190,33443,8.5,37.3,4,Café,Rental Car Location,Construction & Landscaping,Bus Stop,Yoga Studio,Film Studio,Fruit & Vegetable Store,Frozen Yogurt Shop,Fried Chicken Joint,French Restaurant
1,Bexley,51.4549,-0.1505,164,275000,51.8,9075,34350,7.6,39.0,0,Grocery Store,Pub,Fish & Chips Shop,Caucasian Restaurant,Coffee Shop,Plaza,Pizza Place,Park,Fast Food Restaurant,Fish Market
2,Brent,51.5588,-0.2817,169,407250,78.8,15745,29812,7.5,35.6,0,Coffee Shop,Hotel,Clothing Store,Bar,Sporting Goods Shop,Grocery Store,Sandwich Place,Italian Restaurant,Burger Joint,Indian Restaurant
3,Bromley,51.4039,-0.0198,148,374975,64.1,15695,37682,5.3,40.2,3,Café,Pub,Gastropub,Park,Furniture / Home Store,Frozen Yogurt Shop,Fried Chicken Joint,French Restaurant,Forest,Food Court
4,Camden,51.5290,-0.1255,164,700000,123.5,31385,39796,4,36.4,0,Pub,Hotel,Coffee Shop,Café,Sandwich Place,Burger Joint,Italian Restaurant,Bakery,Restaurant,Breakfast Spot

In [78]:
import matplotlib.cm as cm
import matplotlib.colors as colors

In [79]:

# create map
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(London_merged['Latitude'], London_merged['Longitude'], London_merged['Borough'], London_merged['Cluster_Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

## Explore Clusters

### 1st Cluster

In [85]:
London_merged.loc[London_merged['Cluster_Labels'] == 0, London_merged.columns[[0] + list(range(5, London_merged.shape[1]))]]

,Borough,Crime rates,Active businesses,Gross Annual Pay,Unemployment rate,Average Age,Cluster_Labels,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
1,Bexley,51.8,9075,34350,7.6,39.0,0,Grocery Store,Pub,Fish & Chips Shop,Caucasian Restaurant,Coffee Shop,Plaza,Pizza Place,Park,Fast Food Restaurant,Fish Market
2,Brent,78.8,15745,29812,7.5,35.6,0,Coffee Shop,Hotel,Clothing Store,Bar,Sporting Goods Shop,Grocery Store,Sandwich Place,Italian Restaurant,Burger Joint,Indian Restaurant
4,Camden,123.5,31385,39796,4,36.4,0,Pub,Hotel,Coffee Shop,Café,Sandwich Place,Burger Joint,Italian Restaurant,Bakery,Restaurant,Breakfast Spot
5,Croydon,77,15540,32696,4.1,37.0,0,Pub,Coffee Shop,Portuguese Restaurant,Supermarket,Café,Breakfast Spot,Brewery,Malay Restaurant,Burger Joint,Burrito Place
6,Ealing,75.5,18700,31331,5.8,36.2,0,Coffee Shop,Clothing Store,Bakery,Park,Pub,Café,Bus Stop,Vietnamese Restaurant,Pizza Place,Hotel
7,Enfield,69.4,13925,31603,3.8,36.3,0,Coffee Shop,Clothing Store,Café,Gift Shop,Mobile Phone Shop,Shopping Mall,Restaurant,Department Store,Pub,Optical Shop
8,Hackney,99.6,18510,32056,5.9,33.1,0,Pub,Café,Coffee Shop,Bakery,Cocktail Bar,Brewery,Grocery Store,Clothing Store,Organic Grocery,Hotel
9,Haringey,90.2,12675,31063,5.7,35.1,0,Fast Food Restaurant,Pub,Supermarket,Indian Restaurant,Hotel Bar,Light Rail Station,Gym / Fitness Center,Mediterranean Restaurant,Grocery Store,Movie Theater
12,Hillingdon,76.6,13505,33508,5.8,36.4,0,Coffee Shop,Clothing Store,Italian Restaurant,Fast Food Restaurant,Sandwich Place,Pharmacy,Pizza Place,Bookstore,Burger Joint,Supermarket
14,Islington,121.2,22110,36592,4.5,34.8,0,Pub,Mediterranean Restaurant,Cocktail Bar,Theater,Furniture / Home Store,Boutique,Park,Music Venue,Bakery,Burger Joint
15,Kensington and Chelsea,120.9,14350,.,4.2,39.3,0,Café,Restaurant,Clothing Store,Bakery,Grocery Store,Burger Joint,Pub,English Restaurant,Spa,Juice Bar
16,Kingston upon Thames,58.5,8970,37979,4.5,37.1,0,Coffee Shop,Café,Clothing Store,Pub,Italian Restaurant,Bakery,Department Store,Burger Joint,Bookstore,Sushi Restaurant
17,Lambeth,104.6,17280,33441,5.9,34.5,0,Caribbean Restaurant,Market,Pub,Coffee Shop,Mexican Restaurant,Gym / Fitness Center,Pizza Place,Beer Bar,Burger Joint,Cocktail Bar
18,Lewisham,77,10405,33157,5.7,35.0,0,Supermarket,Grocery Store,Italian Restaurant,Pub,Coffee Shop,Train Station,Platform,Portuguese Restaurant,Pharmacy,Dessert Shop
19,Merton,59.7,12070,33989,4.6,36.7,0,Park,Café,Supermarket,Bar,Bus Stop,Garden Center,Burger Joint,Grocery Store,Fast Food Restaurant,Sandwich Place
20,Newham,90.8,11055,27942,9.1,32.1,0,Pub,Italian Restaurant,Hotel,Hostel,Park,Bus Stop,Fast Food Restaurant,Frozen Yogurt Shop,Fried Chicken Joint,French Restaurant
21,Redbridge,69.7,14595,33483,7.9,35.8,0,Pub,Café,Cocktail Bar,Bar,Pizza Place,Italian Restaurant,Turkish Restaurant,Convenience Store,Gastropub,Spanish Restaurant
22,Richmond upon Thames,56.3,14185,42076,3.8,38.8,0,Pub,Coffee Shop,Italian Restaurant,Indian Restaurant,Grocery Store,Pharmacy,Bus Stop,Café,Sandwich Place,Deli / Bodega
23,Southwark,100.6,17120,33864,7.7,34.4,0,Coffee Shop,Pub,Restaurant,Bar,French Restaurant,Scenic Lookout,Cocktail Bar,Pizza Place,Sushi Restaurant,English Restaurant
24,Sutton,55.9,8710,32697,5.5,38.9,0,Clothing Store,Pub,Coffee Shop,Bar,Café,Sandwich Place,Italian Restaurant,Pizza Place,Electronics Store,Park
25,Tower Hamlets,99.9,18390,36429,9.2,31.4,0,Italian Restaurant,Coffee Shop,Hotel,Fried Chicken Joint,Pizza Place,Chinese Restaurant,Gym / Fitness Center,Café,Sandwich Place,Convenience Store
26,Waltham Forest,78,11020,30859,5.4,35.1,0,Pub,Tea Room,Art Gallery,Pool,Beer Store,Pizza Place,Vegetarian / Vegan Restaurant,Gym / Fitness Center,Concert Hall,Coffee Shop
27,Wandsworth,72.6,18695,41064,5.7,35.0,0,Pub,Clothing Store,Coffee Shop,Breakfast Spot,Supermarket,Asian Restaurant,Pizza Place,Chocolate Shop,Burger Joint,Sporting Goods Shop
28,Westminster,212.4,55385,42141,8.8,37.7,0,Coffee Shop,Hotel,Sandwich Place,Theater,Pub,Italian Restaurant,Juice Bar,Sushi Restaurant,Gym / Fitness Center,Sporting Goods Shop

### 2nd Cluster

In [86]:
London_merged.loc[London_merged['Cluster_Labels'] == 1, London_merged.columns[[0] + list(range(5, London_merged.shape[1]))]]

,Borough,Crime rates,Active businesses,Gross Annual Pay,Unemployment rate,Average Age,Cluster_Labels,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
10,Harrow,50.4,15155,33202,4.6,38.3,1,Indian Restaurant,Coffee Shop,Indie Movie Theater,Convenience Store,Supermarket,Platform,Yoga Studio,Farmers Market,Fried Chicken Joint,French Restaurant

### 3rd Cluster

In [87]:
London_merged.loc[London_merged['Cluster_Labels'] == 2, London_merged.columns[[0] + list(range(5, London_merged.shape[1]))]]

,Borough,Crime rates,Active businesses,Gross Annual Pay,Unemployment rate,Average Age,Cluster_Labels,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
11,Havering,62.9,10115,33398,5.3,40.3,2,Park,Breakfast Spot,Forest,Yoga Studio,Garden,Furniture / Home Store,Fruit & Vegetable Store,Frozen Yogurt Shop,Fried Chicken Joint,French Restaurant

### 4th Cluster

In [88]:
London_merged.loc[London_merged['Cluster_Labels'] == 3, London_merged.columns[[0] + list(range(5, London_merged.shape[1]))]]

,Borough,Crime rates,Active businesses,Gross Annual Pay,Unemployment rate,Average Age,Cluster_Labels,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
3,Bromley,64.1,15695,37682,5.3,40.2,3,Café,Pub,Gastropub,Park,Furniture / Home Store,Frozen Yogurt Shop,Fried Chicken Joint,French Restaurant,Forest,Food Court
13,Hounslow,79.2,13910,31001,4.3,35.8,3,Café,Pizza Place,Park,Bed & Breakfast,Yoga Studio,Fast Food Restaurant,Frozen Yogurt Shop,Fried Chicken Joint,French Restaurant,Forest

### 5th Cluster

In [89]:
London_merged.loc[London_merged['Cluster_Labels'] == 4, London_merged.columns[[0] + list(range(5, London_merged.shape[1]))]]

,Borough,Crime rates,Active businesses,Gross Annual Pay,Unemployment rate,Average Age,Cluster_Labels,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,Barnet,62.7,26190,33443,8.5,37.3,4,Café,Rental Car Location,Construction & Landscaping,Bus Stop,Yoga Studio,Film Studio,Fruit & Vegetable Store,Frozen Yogurt Shop,Fried Chicken Joint,French Restaurant